import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type, apikey','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const enc=new TextEncoder(),clean=(v:any,n=500)=>String(v??'').trim().slice(0,n),now=()=>new Date().toISOString();
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
 try{
  const ah=req.headers.get('authorization')||'',tok=ah.startsWith('Bearer ')?ah.slice(7).trim():'';if(!tok)return json({error:'UNAUTHORIZED'},401);
  const th=await hash(tok),{data:ss}=await sb.from('staff_sessions').select('id,user_id,expires_at,revoked_at').eq('token_hash',th).maybeSingle();if(!ss||ss.revoked_at||new Date(ss.expires_at).getTime()<=Date.now())return json({error:'SESSION_EXPIRED'},401);
  const {data:st}=await sb.from('staff_accounts').select('is_active').eq('user_id',ss.user_id).maybeSingle();if(!st?.is_active)return json({error:'FORBIDDEN'},403);
  const {data:pm}=await sb.from('staff_permissions').select('permission_code').eq('user_id',ss.user_id).eq('permission_code','kids.manage').eq('is_allowed',true).maybeSingle();if(!pm)return json({error:'FORBIDDEN'},403);
  await sb.from('staff_sessions').update({last_seen_at:now()}).eq('id',ss.id);
  const b=await req.json(),a=clean(b.action,60);
  if(a==='dashboard'){const qs=await Promise.all([sb.from('kids_content_items').select('*',{count:'exact',head:true}),sb.from('kids_content_items').select('*',{count:'exact',head:true}).eq('status','published'),sb.from('kids_content_items').select('*',{count:'exact',head:true}).eq('status','draft'),sb.from('kids_content_items').select('*',{count:'exact',head:true}).in('commercial_mode',['paid','product_linked','mixed']),sb.from('kids_characters').select('*',{count:'exact',head:true}).eq('is_active',true),sb.from('kids_content_assets').select('*',{count:'exact',head:true}),sb.from('program_content_items').select('*',{count:'exact',head:true}),sb.from('kids_product_links').select('*',{count:'exact',head:true})]);return json({stats:{content:qs[0].count||0,published:qs[1].count||0,drafts:qs[2].count||0,commercial:qs[3].count||0,characters:qs[4].count||0,assets:qs[5].count||0,program_links:qs[6].count||0,product_links:qs[7].count||0}})}
  if(a==='refs'){const qs=await Promise.all([sb.from('kids_content_categories').select('*').eq('is_active',true).order('sort_order'),sb.from('kids_age_groups').select('*').eq('is_active',true).order('sort_order'),sb.from('kids_characters').select('*').eq('is_active',true).order('sort_order'),sb.from('kids_levels').select('*').eq('is_active',true).order('sort_order'),sb.from('am_programs').select('id,code,name,audience_code,is_active').eq('is_active',true).order('sort_order'),sb.from('store_products').select('id,sku,name,base_price,currency,is_active').eq('is_active',true).order('sort_order')]);return json({categories:qs[0].data||[],age_groups:qs[1].data||[],characters:qs[2].data||[],levels:qs[3].data||[],programs:qs[4].data||[],products:qs[5].data||[]})}
  if(a==='list_content'){let q=sb.from('kids_content_items').select('*,kids_content_categories(name,code)').order('sort_order').order('created_at',{ascending:false});if(b.content_type&&b.content_type!=='all')q=q.eq('content_type',b.content_type);if(b.status&&b.status!=='all')q=q.eq('status',b.status);const r=await q.limit(500);if(r.error)throw r.error;return json({items:r.data||[]})}
  if(a==='get_content'){const id=clean(b.id,80);const qs=await Promise.all([sb.from('kids_content_items').select('*').eq('id',id).single(),sb.from('kids_content_assets').select('*').eq('content_item_id',id).order('sort_order'),sb.from('kids_content_age_groups').select('age_group_id').eq('content_item_id',id),sb.from('kids_content_characters').select('character_id,role_code,sort_order').eq('content_item_id',id).order('sort_order'),sb.from('program_content_items').select('*,am_programs(name,code,audience_code)').eq('content_item_id',id).order('sequence_no'),sb.from('kids_product_links').select('*,store_products(name,sku,base_price,currency)').eq('content_item_id',id).order('sort_order')]);if(qs[0].error)throw qs[0].error;return json({item:qs[0].data,assets:qs[1].data||[],age_groups:(qs[2].data||[]).map((x:any)=>x.age_group_id),characters:qs[3].data||[],program_links:qs[4].data||[],product_links:qs[5].data||[]})}
  if(a==='save_content'){const x=b.item||{},types=['story','coloring','song','activity','mission','printable','worksheet','quiz','certificate','video','audio','around_the_world','character_activity'],type=clean(x.content_type||'story',40),cm=clean(x.commercial_mode||'included_program',40),status=clean(x.status||'draft',30);if(!types.includes(type))return json({error:'INVALID_CONTENT_TYPE'},400);if(!['free','paid','included_program','product_linked','institution_licensed','mixed'].includes(cm))return json({error:'INVALID_COMMERCIAL_MODE'},400);if(!['draft','review','published','archived'].includes(status))return json({error:'INVALID_STATUS'},400);const p:any={code:clean(x.code,100),title:clean(x.title,220),content_type:type,category_id:x.category_id||null,language_code:clean(x.language_code||'en',10),short_description:clean(x.short_description,800)||null,description:clean(x.description,5000)||null,duration_minutes:x.duration_minutes===''||x.duration_minutes==null?null:Number(x.duration_minutes),access_level:clean(x.access_level||'program_only',40),level_id:x.level_id||null,season_id:x.season_id||null,mission_id:x.mission_id||null,status,is_featured:!!x.is_featured,sort_order:Number(x.sort_order||999),commercial_mode:cm,base_price:Number(x.base_price||0),currency:clean(x.currency||'EGP',10),price_unit:clean(x.price_unit||'per_item',30),allow_direct_purchase:!!x.allow_direct_purchase,commercial_notes:clean(x.commercial_notes,2000)||null,published_at:status==='published'?(x.published_at||now()):null,updated_at:now()};if(!p.code||!p.title)return json({error:'CODE_AND_TITLE_REQUIRED'},400);const r=x.id?await sb.from('kids_content_items').update(p).eq('id',x.id).select().single():await sb.from('kids_content_items').insert(p).select().single();if(r.error)throw r.error;const id=r.data.id;if(Array.isArray(b.age_groups)){await sb.from('kids_content_age_groups').delete().eq('content_item_id',id);if(b.age_groups.length){const z=await sb.from('kids_content_age_groups').insert(b.age_groups.map((age_group_id:string)=>({content_item_id:id,age_group_id})));if(z.error)throw z.error}}if(Array.isArray(b.characters)){await sb.from('kids_content_characters').delete().eq('content_item_id',id);const rows=b.characters.map((character_id:string,i:number)=>({content_item_id:id,character_id,role_code:'featured',sort_order:i}));if(rows.length){const z=await sb.from('kids_content_characters').insert(rows);if(z.error)throw z.error}}return json({ok:true,item:r.data})}
  if(a==='upload_asset'){const id=clean(b.content_item_id,80),at=clean(b.asset_type||'other',30),fn=clean(b.filename||'asset.bin',220),ct=clean(b.content_type||'application/octet-stream',100),b64=String(b.data_base64||'');if(!id||!b64)return json({error:'MISSING_ASSET_DATA'},400);const {data:item}=await sb.from('kids_content_items').select('access_level,commercial_mode').eq('id',id).single();if(!item)return json({error:'CONTENT_NOT_FOUND'},404);const publicAsset=['cover','thumbnail'].includes(at)||['free','public_preview'].includes(item.access_level);const bucket=publicAsset?'kids-assets':'kids-protected-assets',protectedFlag=!publicAsset;const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(bytes.length>10*1024*1024)return json({error:'ASSET_TOO_LARGE'},413);const safe=fn.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`content/${id}/${Date.now()}-${safe}`;const up=await sb.storage.from(bucket).upload(path,bytes,{contentType:ct,upsert:false});if(up.error)throw up.error;const r=await sb.from('kids_content_assets').insert({content_item_id:id,asset_type:at,storage_path:path,file_name:fn,mime_type:ct,language_code:clean(b.language_code||'en',10),is_primary:!!b.is_primary,is_downloadable:!!b.is_downloadable,sort_order:Number(b.sort_order||999),storage_bucket:bucket,is_protected:protectedFlag}).select().single();if(r.error)throw r.error;if(at==='cover')await sb.from('kids_content_items').update({cover_image_path:path,updated_at:now()}).eq('id',id);if(at==='thumbnail')await sb.from('kids_content_items').update({thumbnail_path:path,updated_at:now()}).eq('id',id);return json({ok:true,asset:r.data})}
  if(a==='delete_asset'){const id=clean(b.id,80),{data:x}=await sb.from('kids_content_assets').select('*').eq('id',id).maybeSingle();if(!x)return json({error:'NOT_FOUND'},404);await sb.storage.from(x.storage_bucket||'kids-assets').remove([x.storage_path]);await sb.from('kids_content_assets').delete().eq('id',id);if(x.asset_type==='cover')await sb.from('kids_content_items').update({cover_image_path:null,updated_at:now()}).eq('id',x.content_item_id).eq('cover_image_path',x.storage_path);if(x.asset_type==='thumbnail')await sb.from('kids_content_items').update({thumbnail_path:null,updated_at:now()}).eq('id',x.content_item_id).eq('thumbnail_path',x.storage_path);return json({ok:true})}
  if(a==='delete_content'){const id=clean(b.id,80),{data:as}=await sb.from('kids_content_assets').select('storage_path,storage_bucket').eq('content_item_id',id);for(const bucket of ['kids-assets','kids-protected-assets']){const ps=(as||[]).filter((x:any)=>(x.storage_bucket||'kids-assets')===bucket).map((x:any)=>x.storage_path);if(ps.length)await sb.storage.from(bucket).remove(ps)}const r=await sb.from('kids_content_items').delete().eq('id',id);if(r.error)throw r.error;return json({ok:true})}
  if(a==='save_program_links'){const id=clean(b.content_item_id,80);await sb.from('program_content_items').delete().eq('content_item_id',id);const rows=(Array.isArray(b.links)?b.links:[]).filter((x:any)=>x.program_id).map((x:any,i:number)=>({program_id:x.program_id,content_item_id:id,sequence_no:Number(x.sequence_no||((i+1)*10)),is_required:x.is_required!==false,delivery_mode:x.delivery_mode||'instructor_led',learner_visibility:x.learner_visibility||'during_program',instructor_notes:clean(x.instructor_notes,1200)||null}));if(rows.length){const r=await sb.from('program_content_items').insert(rows);if(r.error)throw r.error}return json({ok:true})}
  if(a==='save_product_links'){const id=clean(b.content_item_id,80);await sb.from('kids_product_links').delete().eq('content_item_id',id);const rows=(Array.isArray(b.links)?b.links:[]).filter((x:any)=>x.product_id).map((x:any,i:number)=>({content_item_id:id,product_id:x.product_id,link_type:x.link_type||'recommended',sort_order:i}));if(rows.length){const r=await sb.from('kids_product_links').insert(rows);if(r.error)throw r.error}return json({ok:true})}
  return json({error:'INVALID_ACTION'},400)
 }catch(e){console.error(e);return json({error:'SERVER_ERROR',detail:String((e as any)?.message||e)},500)}
});