import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';

const SUPABASE_URL = 'https://vsuekfzyebqnhthyvwpf.supabase.co';
const SUPABASE_KEY = 'sb_publishable_sRvoFKXyDEzQPLaAk3xZOQ_RLVxh5g3';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const dict = {
  ar:{dir:'rtl',hero:'ابدأ رحلتك في عالم الطيران',heroSub:'Aviation Matrix نظام لاكتشاف وتطوير المواهب في الطيران، من أول التقديم لحد بناء ملف مهني ومسار مناسب.',start:'ابدأ تقييمك المبدئي',journey:'رحلتك تبدأ قبل التخصص',journeySub:'مش بنبيع كورس واحد للجميع. بنبني صورة مهنية تدريجيًا.',reg:'التسجيل والتقييم المبدئي',fit:'Current Fit + Future Fit',learn:'My Journey',privacy:'بياناتك تستخدم لبدء التقييم والتواصل فقط.',welcome:'بدأنا نبني ملفك المهني',confirm:'تأكيد الملف',assess:'التقييم المبدئي',results:'النتائج',dashboard:'My Journey',continue:'متابعة',next:'السؤال التالي',finish:'عرض النتيجة'},
  en:{dir:'ltr',hero:'Start Your Journey in Aviation',heroSub:'Aviation Matrix is an aviation talent intelligence and development system, from application to a verified professional journey.',start:'Start Initial Assessment',journey:'Your journey starts before specialization',journeySub:'We do not sell one course to everyone. We build a professional picture over time.',reg:'Registration & Initial Assessment',fit:'Current Fit + Future Fit',learn:'My Journey',privacy:'Your data is used only to start assessment and communication.',welcome:'We started building your professional profile',confirm:'Confirm Profile',assess:'Initial Assessment',results:'Results',dashboard:'My Journey',continue:'Continue',next:'Next question',finish:'View results'},
  fr:{dir:'ltr',hero:'Commencez votre parcours dans l’aviation',heroSub:'Aviation Matrix est un système d’intelligence et de développement des talents dans l’aviation.',start:'Commencer l’évaluation initiale',journey:'Votre parcours commence avant la spécialisation',journeySub:'Nous ne vendons pas le même cours à tout le monde. Nous construisons un profil professionnel dans le temps.',reg:'Inscription & évaluation initiale',fit:'Adéquation actuelle + future',learn:'Mon parcours',privacy:'Vos données sont utilisées uniquement pour démarrer l’évaluation et la communication.',welcome:'Nous avons commencé à construire votre profil professionnel',confirm:'Confirmer le profil',assess:'Évaluation initiale',results:'Résultats',dashboard:'Mon parcours',continue:'Continuer',next:'Question suivante',finish:'Voir les résultats'},
  ru:{dir:'ltr',hero:'Начните свой путь в авиации',heroSub:'Aviation Matrix — система оценки и развития авиационных талантов: от заявки до профессионального маршрута.',start:'Начать первичную оценку',journey:'Ваш путь начинается до специализации',journeySub:'Мы не продаём один курс всем. Мы постепенно строим профессиональный профиль.',reg:'Регистрация и первичная оценка',fit:'Текущая + будущая пригодность',learn:'Мой путь',privacy:'Ваши данные используются только для начала оценки и связи.',welcome:'Мы начали формировать ваш профессиональный профиль',confirm:'Подтвердить профиль',assess:'Первичная оценка',results:'Результаты',dashboard:'Мой путь',continue:'Продолжить',next:'Следующий вопрос',finish:'Показать результаты'}
};

const questions = [
 {dim:'communication',q:'مسافر متضايق وبيتحدث بصوت عالي. أول تصرف ليك؟',opts:[['أسمع المشكلة كاملة وأهدي الموقف',95],['أشرح القواعد مباشرة',76],['أطلب من زميل يتدخل',64],['أطلب منه يهدى قبل أي نقاش',54]]},
 {dim:'teamwork',q:'زميلك متأخر في تنفيذ جزء من مهمة مشتركة، تعمل إيه؟',opts:[['أتأكد من السبب وأساعد في إعادة توزيع العمل',92],['أنفذ الجزء بتاعه من غير ما أتكلم',70],['أبلغ المسؤول فورًا قبل ما أفهم السبب',58],['أسيبه يتحمل النتيجة وحده',40]]},
 {dim:'attention',q:'لاحظت اختلاف صغير بين رقم في النظام والمستند الورقي.',opts:[['أوقف الإجراء وأتحقق من المصدرين',96],['أكمل لأن الفرق صغير',38],['أسأل زميل فقط',66],['أعدل الرقم الأقرب للمنطق',30]]},
 {dim:'judgment',q:'عندك ضغط وقت ومعلومة ناقصة تؤثر على القرار.',opts:[['أحدد المعلومة الحرجة وأصعّد لو لازم',94],['أخمن وأكمل',32],['أنتظر بدون تواصل',54],['أختار أسرع حل متاح',62]]},
 {dim:'customer',q:'عميل طلب حاجة خارج الإجراء المعتاد.',opts:[['أوضح المتاح وأبحث عن بديل مسموح',93],['أرفض مباشرة',55],['أوافق عشان أرضيه',35],['أحوله لشخص آخر فورًا',67]]},
 {dim:'digital',q:'ظهرلك نظام جديد في الشغل لأول مرة.',opts:[['أتعلم الأساسيات وأجرب في بيئة آمنة',90],['أفضل الورق فقط',40],['أستنى حد يعمله مكاني',35],['أستخدمه مباشرة بدون فهم',52]]},
 {dim:'english',q:'لو وصلك Instruction بالإنجليزي وفي مصطلح مش واضح.',opts:[['أتأكد من المصطلح قبل التنفيذ',92],['أعتمد على التخمين',35],['أتجاهل الجزء غير الواضح',28],['أترجم ترجمة سريعة وأنفذ فورًا',66]]},
 {dim:'communication',q:'مطلوب منك توصل معلومة مهمة في وقت قصير.',opts:[['أذكر المعلومة الأساسية والتأثير والخطوة المطلوبة',95],['أحكي كل التفاصيل من البداية',68],['أرسل كلمة أو جملة مختصرة جدًا',50],['أؤجل الرسالة لوقت أهدى',40]]},
 {dim:'teamwork',q:'في اختلاف رأي داخل الفريق على أولوية التنفيذ.',opts:[['نرجع للهدف/الإجراء ونحدد الأولوية بوضوح',94],['كل شخص يعمل بطريقته',34],['أمشي رأيي لأنه الأسرع',48],['نوقف كل شيء لحد المدير',60]]},
 {dim:'judgment',q:'أي وصف أقرب لك في مهنة الطيران؟',opts:[['أفضل العمل المنظم والمسؤولية والتعلم المستمر',92],['أهم شيء شكل الوظيفة والسفر',44],['أفضل الوظائف بدون ضغط أو إجراءات',38],['لسه بستكشف ومحتاج أعرف المسارات',78]]}
];

let lang = localStorage.getItem('am_lang') || 'ar';
let state = JSON.parse(localStorage.getItem('am_state') || '{}');
let assessment = {index:0,answers:[],scores:{communication:0,teamwork:0,attention:0,judgment:0,customer:0,digital:0,english:0},counts:{communication:0,teamwork:0,attention:0,judgment:0,customer:0,digital:0,english:0}};

const app = document.getElementById('app');
function t(k){return dict[lang][k]||k}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function setLang(l){lang=l;localStorage.setItem('am_lang',l);document.documentElement.lang=l;document.documentElement.dir=dict[l].dir;render()}
function saveState(){localStorage.setItem('am_state',JSON.stringify(state))}

function header(){return `<div class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-mark">✈</div><div>Aviation Matrix<small>Talent Intelligence & Development</small></div></div><div class="lang">${['ar','en','fr','ru'].map(l=>`<button data-lang="${l}" class="${lang===l?'active':''}">${l.toUpperCase()}</button>`).join('')}</div></div></div>`}

function landing(){return `<div class="shell">${header()}<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Aviation Talent Intelligence System</span><h1>${t('hero')}</h1><p>${t('heroSub')}</p><div class="cta-row"><button class="btn btn-primary" id="startBtn">${t('start')}</button><button class="btn btn-outline" data-scroll="journey">${t('journey')}</button></div></div><div class="hero-card"><h3>${t('reg')}</h3><div class="mini-list"><div class="mini-item">01 — Applicant Profile</div><div class="mini-item">02 — Initial Aviation Assessment</div><div class="mini-item">03 — Current / Future Fit</div><div class="mini-item">04 — Suggested Aviation Path</div><div class="mini-item">05 — My Journey</div></div></div></div></section><section class="section" id="journey"><div class="container"><h2>${t('journey')}</h2><p class="section-lead">${t('journeySub')}</p><div class="grid-3"><div class="card info-card"><strong>${t('reg')}</strong><p>Lead → Profile → Assessment</p></div><div class="card info-card"><strong>${t('fit')}</strong><p>Strengths, gaps and path options.</p></div><div class="card info-card"><strong>${t('learn')}</strong><p>Learning, documents, technical English and assessments.</p></div></div></div></section><footer class="footer"><div class="container">Aviation Matrix · ${t('privacy')}</div></footer></div>`}

function registrationModal(){return `<div class="overlay" id="regOverlay"><div class="modal"><div class="modal-head"><div><h2 style="margin:0">${t('reg')}</h2><p class="muted">No CV upload — your professional profile will be built inside Aviation Matrix.</p></div><button class="close" id="closeModal">×</button></div><form id="regForm"><div class="form-grid"><div class="field"><label>Full name</label><input name="full_name" required value="${esc(state.full_name||'')}"></div><div class="field"><label>Mobile</label><input name="mobile" required value="${esc(state.mobile||'')}"></div><div class="field"><label>Email</label><input type="email" name="email" required value="${esc(state.email||'')}"></div><div class="field"><label>Date of birth</label><input type="date" name="date_of_birth" required value="${esc(state.date_of_birth||'')}"></div><div class="field"><label>Education stage</label><select name="education_stage"><option value="school">School</option><option value="secondary">Secondary</option><option value="university">University</option><option value="graduate">Graduate</option><option value="other">Other</option></select></div><div class="field"><label>Current city</label><input name="current_city" required value="${esc(state.current_city||'')}"></div><div class="field"><label>Aviation interest</label><select name="aviation_interest"><option value="cabin_crew">Cabin Crew</option><option value="passenger_services">Passenger Services</option><option value="cargo">Cargo</option><option value="ground_operations">Ground Operations</option><option value="flight_ops">Flight Operations</option><option value="not_sure">Not sure yet</option></select></div><div class="field"><label>Preferred communication language</label><select name="preferred_language"><option value="ar">Arabic</option><option value="en">English</option><option value="ar_en">Arabic / English</option></select></div><div class="field full"><div class="check"><input type="checkbox" name="consent" id="consent" required><label for="consent">${t('privacy')}</label></div></div><div class="field full"><div id="regMsg" class="helper"></div><button class="btn btn-dark" type="submit">${t('continue')}</button></div></div></form></div></div>`}

function flowShell(content,step,pct){const steps=[t('confirm'),t('assess'),t('results'),t('dashboard')];return `${header()}<main class="container flow"><div class="progress"><div style="width:${pct}%"></div></div><div class="stepbar">${steps.map((s,i)=>`<span class="step ${i+1<step?'done':''} ${i+1===step?'active':''}">${s}</span>`).join('')}</div><div class="card screen-card">${content}</div></main>`}

function welcome(){return flowShell(`<span class="eyebrow" style="color:var(--navy);border-color:var(--line)">Journey Started</span><h1>${t('welcome')}</h1><p class="section-lead">${esc(state.full_name||'Candidate')}, your application is registered. Now we confirm your profile, run a short aviation assessment, and build your first Current/Future Fit.</p><div class="grid-2"><div class="info-card" style="background:#f5f8fb;border-radius:18px"><strong>Profile status</strong><p>Declared data</p></div><div class="info-card" style="background:#f5f8fb;border-radius:18px"><strong>Next step</strong><p>${t('confirm')}</p></div></div><div class="cta-row"><button class="btn btn-dark" id="confirmBtn">${t('confirm')}</button></div>`,1,20)}

function confirmProfile(){return flowShell(`<h1>${t('confirm')}</h1><p class="section-lead">Confirm the non-sensitive basics you submitted. Verification will be a separate stage later.</p><div class="form-grid"><div class="field"><label>Full name</label><input id="pName" value="${esc(state.full_name||'')}"></div><div class="field"><label>City</label><input id="pCity" value="${esc(state.current_city||'')}"></div><div class="field"><label>Education</label><input value="${esc(state.education_stage||'')}" disabled></div><div class="field"><label>Interest</label><input value="${esc(state.aviation_interest||'')}" disabled></div></div><div class="cta-row"><button class="btn btn-dark" id="beginAssessment">${t('assess')}</button></div>`,1,25)}

function assessmentScreen(){const q=questions[assessment.index];const pct=30+Math.round((assessment.index/questions.length)*35);return flowShell(`<div class="question-meta">Question ${assessment.index+1} / ${questions.length} · ${q.dim}</div><h2>${q.q}</h2><div class="options">${q.opts.map((o,i)=>`<button class="option" data-opt="${i}" data-score="${o[1]}">${o[0]}</button>`).join('')}</div><div class="cta-row"><button class="btn btn-dark hidden" id="nextQuestion">${assessment.index===questions.length-1?t('finish'):t('next')}</button></div>`,2,pct)}

function computeResult(){const dims={};Object.keys(assessment.scores).forEach(k=>dims[k]=assessment.counts[k]?Math.round(assessment.scores[k]/assessment.counts[k]):0);const avg=Math.round(Object.values(dims).reduce((a,b)=>a+b,0)/Object.values(dims).filter(x=>x>0).length);const future=Math.min(96,avg+12);let path='Passenger Services';if((dims.communication+dims.customer+dims.english)/3>=80)path='Cabin Crew';else if(dims.attention>=85&&dims.judgment>=80)path='Flight Operations Support';else if(dims.digital>=82&&dims.attention>=80)path='Cargo';else if(dims.teamwork>=82)path='Ground Operations';const gaps=Object.entries(dims).filter(([,v])=>v<78).sort((a,b)=>a[1]-b[1]).slice(0,3).map(([k])=>k);return{dims,current:avg,future,path,gaps}}

function results(){const r=computeResult();state.result=r;saveState();return flowShell(`<h1>${t('results')}</h1><p class="section-lead">Pilot rule-based result — not a psychometric diagnosis. It shows your current signals and development potential.</p><div class="result-hero"><div class="fit-card"><span class="muted">Current Fit</span><b>${r.current}%</b><p class="muted">Your current combined readiness signal.</p></div><div class="fit-card"><span class="muted">Future Fit</span><b>${r.future}%</b><p class="muted">Potential after targeted development.</p></div></div><h3>Suggested Aviation Path</h3><div class="path-list"><div class="path best"><strong>${r.path}</strong><div class="muted">Best current fit based on this pilot assessment.</div></div><div class="path"><strong>Alternative 1</strong><div class="muted">Passenger Services / Ground Operations depending on your detailed profile.</div></div><div class="path"><strong>Alternative 2</strong><div class="muted">Cargo / Aviation Administration as secondary options.</div></div></div><h3>Development Gaps</h3><div class="grid-3">${(r.gaps.length?r.gaps:['technical_english']).map(g=>`<div class="info-card" style="background:#f5f8fb;border-radius:16px"><strong>${g.replaceAll('_',' ')}</strong><p>Developable — not a rejection reason.</p></div>`).join('')}</div><div class="cta-row"><button class="btn btn-dark" id="openDashboard">${t('dashboard')}</button></div>`,3,78)}

function dashboard(){const r=state.result||computeResult();return flowShell(`<h1>${t('dashboard')}</h1><p class="section-lead">Your first Aviation Matrix profile is now active.</p><div class="dashboard-grid"><div><div class="metric-grid"><div class="metric"><span>Profile</span><b>80%</b></div><div class="metric"><span>Assessment</span><b>100%</b></div><div class="metric"><span>Current Fit</span><b>${r.current}%</b></div><div class="metric"><span>Future Fit</span><b>${r.future}%</b></div></div><div class="card info-card"><strong>Suggested Path</strong><h2 style="margin:8px 0">${r.path}</h2><p>Next: open your first aviation foundation journey.</p></div></div><div class="module-list"><div class="module"><span>Learning Journey</span><span class="pill ok">Ready next</span></div><div class="module"><span>Documents</span><span class="pill">Later</span></div><div class="module"><span>Technical English</span><span class="pill">Planned</span></div><div class="module"><span>Assessments</span><span class="pill ok">Initial done</span></div><div class="module"><span>Airline Matching</span><span class="pill">Future stage</span></div></div></div>`,4,100)}

function bindCommon(){document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)))}
function render(view=state.view||'landing'){
  state.view=view;saveState();
  if(view==='landing')app.innerHTML=landing();
  if(view==='welcome')app.innerHTML=welcome();
  if(view==='confirm')app.innerHTML=confirmProfile();
  if(view==='assessment')app.innerHTML=assessmentScreen();
  if(view==='results')app.innerHTML=results();
  if(view==='dashboard')app.innerHTML=dashboard();
  bindCommon();
  if(view==='landing'){
    document.getElementById('startBtn').addEventListener('click',()=>{document.body.insertAdjacentHTML('beforeend',registrationModal());bindModal()});
    document.querySelector('[data-scroll]')?.addEventListener('click',()=>document.getElementById('journey').scrollIntoView({behavior:'smooth'}));
  }
  if(view==='welcome')document.getElementById('confirmBtn').addEventListener('click',()=>render('confirm'));
  if(view==='confirm')document.getElementById('beginAssessment').addEventListener('click',()=>{state.full_name=document.getElementById('pName').value.trim();state.current_city=document.getElementById('pCity').value.trim();saveState();assessment={index:0,answers:[],scores:{communication:0,teamwork:0,attention:0,judgment:0,customer:0,digital:0,english:0},counts:{communication:0,teamwork:0,attention:0,judgment:0,customer:0,digital:0,english:0}};render('assessment')});
  if(view==='assessment')bindAssessment();
  if(view==='results')document.getElementById('openDashboard').addEventListener('click',()=>render('dashboard'));
}

function bindModal(){
 document.getElementById('closeModal').addEventListener('click',()=>document.getElementById('regOverlay').remove());
 const form=document.getElementById('regForm');
 form.addEventListener('submit',async e=>{
   e.preventDefault(); const fd=new FormData(form); const payload=Object.fromEntries(fd.entries());payload.consent=fd.get('consent')==='on';payload.source='landing_pilot';
   const msg=document.getElementById('regMsg'); msg.textContent='Saving...';
   const {error}=await supabase.from('aviation_interest_leads').insert(payload);
   if(error){msg.innerHTML=`<span class="error">${esc(error.message)}</span>`;return;}
   state={...state,...payload,view:'welcome'};saveState();document.getElementById('regOverlay').remove();render('welcome');
 });
}

function bindAssessment(){
 let selected=null;document.querySelectorAll('.option').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selected={idx:Number(btn.dataset.opt),score:Number(btn.dataset.score)};document.getElementById('nextQuestion').classList.remove('hidden')}));
 document.getElementById('nextQuestion').addEventListener('click',()=>{if(!selected)return;const q=questions[assessment.index];assessment.answers.push({question:assessment.index,dimension:q.dim,score:selected.score,option:selected.idx});assessment.scores[q.dim]+=selected.score;assessment.counts[q.dim]++;if(assessment.index===questions.length-1){render('results')}else{assessment.index++;render('assessment')}});
}

render();
