import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const enc=new TextEncoder();const now=()=>new Date().toISOString();const clean=(v:any,n=500)=>String(v??'').trim().slice(0,n);
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function sha(s:string){const h=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function clientIp(req:Request){return clean(req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]||'unknown',120)}
const emailOk=(s:string)=>!s||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
const dateOk=(s:string)=>!s||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(new Date(`${s}T00:00:00Z`).getTime())&&new Date(`${s}T00:00:00Z`).getTime()<=Date.now());
async function rate(admin:any,raw:string,action:string,max:number,windowSeconds:number){const scope=await sha(`registration-v1|${raw}`);const {data,error}=await admin.rpc('am_check_public_api_rate_limit',{p_scope_hash:scope,p_action:action,p_window_seconds:windowSeconds,p_max_requests:max});if(error)throw error;return data}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const len=Number(req.headers.get('content-length')||0);if(len>16777216)return json({error:'REQUEST_TOO_LARGE'},413);
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
 try{const body=await req.json(),action=clean(body.action,80),ip=clientIp(req);
  if(action==='request_registration'){
   const full_name=clean(body.full_name,220),email=clean(body.email,220).toLowerCase()||null,mobile=clean(body.mobile,80).replace(/\s+/g,'')||null,dob=clean(body.date_of_birth,20)||null,programCode=clean(body.program_code,100)||null;
   if(!full_name||(!email&&!mobile))return json({error:'NAME_AND_CONTACT_REQUIRED'},400);if(email&&!emailOk(email))return json({error:'INVALID_EMAIL'},400);if(dob&&!dateOk(dob))return json({error:'INVALID_DATE_OF_BIRTH'},400);
   const rl1=await rate(admin,ip,'registration_request_ip',20,3600);if(!rl1?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rl1?.retry_after_seconds||60},429);
   const rl2=await rate(admin,`${email||mobile}`,'registration_request_contact',3,3600);if(!rl2?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rl2?.retry_after_seconds||60},429);
   if(programCode){const {data:p}=await admin.from('am_programs').select('code').eq('code',programCode).eq('is_active',true).maybeSingle();if(!p)return json({error:'PROGRAM_NOT_AVAILABLE'},400)}
   const r=await admin.from('am_registration_applications').insert({intake_type:'individual',full_name,email,mobile,date_of_birth:dob,current_city:clean(body.current_city,120)||null,preferred_language:clean(body.preferred_language,20)||'en',source_code:'direct',program_code:programCode,lifecycle_status:'submitted'}).select().single();if(r.error)throw r.error;
   await admin.from('am_registration_events').insert({application_id:r.data.id,event_code:'REGISTRATION_REQUESTED',title:'Registration request submitted',actor_type:'applicant'});return json({ok:true,application_number:r.data.application_number,status:'submitted'})
  }
  if(action==='verify_code'){
   const appNo=clean(body.application_number,80),code=clean(body.code,20).toUpperCase(),batch=clean(body.batch_code,80).toUpperCase();
   const rv=await rate(admin,`${ip}|${appNo}`,'registration_verify_code',12,900);if(!rv?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rv?.retry_after_seconds||60},429);
   const {data:a}=await admin.from('am_registration_applications').select('*,am_institution_batches(batch_code)').eq('application_number',appNo).maybeSingle();if(!a)return json({error:'CODE_EXPIRED_OR_INVALID'},401);
   if(a.intake_type==='institution_bulk'&&clean(a.am_institution_batches?.batch_code,80).toUpperCase()!==batch)return json({error:'CODE_EXPIRED_OR_INVALID'},401);
   const {data:c}=await admin.from('am_registration_activation_codes').select('*').eq('application_id',a.id).is('revoked_at',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!c||c.consumed_at||new Date(c.expires_at).getTime()<=Date.now())return json({error:'CODE_EXPIRED_OR_INVALID'},401);if(Number(c.attempt_count||0)>=Number(c.max_attempts||5))return json({error:'CODE_LOCKED'},429);
   const h=await sha(code);if(h!==c.code_hash){await admin.from('am_registration_activation_codes').update({attempt_count:Number(c.attempt_count||0)+1}).eq('id',c.id);return json({error:'INVALID_CODE'},401)}
   await admin.from('am_registration_activation_codes').update({verified_at:now(),consumed_at:now(),attempt_count:Number(c.attempt_count||0)+1}).eq('id',c.id);const t=token(),th=await sha(t),exp=new Date(Date.now()+7*24*3600*1000).toISOString();await admin.from('am_registration_sessions').insert({application_id:a.id,token_hash:th,expires_at:exp});await admin.from('am_registration_applications').update({lifecycle_status:'registration_in_progress',contact_verification_status:'verified',updated_at:now()}).eq('id',a.id);await admin.rpc('am_recalculate_registration_gate',{p_application_id:a.id});return json({ok:true,registration_token:t,expires_at:exp,application_number:a.application_number})
  }
  const rt=clean(body.registration_token,200);if(!rt)return json({error:'REGISTRATION_TOKEN_REQUIRED'},401);const th=await sha(rt);
  const sessionRate=await rate(admin,th,'registration_session',120,900);if(!sessionRate?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:sessionRate?.retry_after_seconds||60},429);
  const {data:s}=await admin.from('am_registration_sessions').select('*,am_registration_applications(*)').eq('token_hash',th).maybeSingle();if(!s||s.revoked_at||new Date(s.expires_at).getTime()<=Date.now())return json({error:'REGISTRATION_SESSION_EXPIRED'},401);const a=s.am_registration_applications;
  if(action==='get_onboarding'){const [{data:reqs},{data:docs},{data:cons},{data:pays}]=await Promise.all([admin.rpc('am_registration_required_documents',{p_application_id:a.id}),admin.from('am_application_documents').select('*,am_document_type_registry(code,name)').eq('application_id',a.id).order('created_at',{ascending:false}),admin.from('am_application_consents').select('*').eq('application_id',a.id).order('created_at',{ascending:false}),admin.from('am_registration_payment_refs').select('*').eq('application_id',a.id).order('created_at',{ascending:false})]);const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:a.id});const {data:f}=await admin.from('am_registration_applications').select('*').eq('id',a.id).single();return json({application:f,requirements:reqs||[],documents:docs||[],consents:cons||[],payments:pays||[],gate:g})}
  if(action==='save_profile'){
   const x=body.profile||{},patch:any={updated_at:now()};
   if(Object.prototype.hasOwnProperty.call(x,'full_name'))patch.full_name=clean(x.full_name,220)||null;
   if(Object.prototype.hasOwnProperty.call(x,'current_city'))patch.current_city=clean(x.current_city,120)||null;
   if(Object.prototype.hasOwnProperty.call(x,'preferred_language'))patch.preferred_language=clean(x.preferred_language,20)||'en';
   if(Object.prototype.hasOwnProperty.call(x,'date_of_birth')){const d=clean(x.date_of_birth,20)||null;if(d&&!dateOk(d))return json({error:'INVALID_DATE_OF_BIRTH'},400);patch.date_of_birth=d}
   await admin.from('am_registration_applications').update(patch).eq('id',a.id);const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:a.id});return json({ok:true,gate:g})
  }
  if(action==='accept_consent'){await admin.from('am_application_consents').insert({application_id:a.id,consent_code:'PLATFORM_REGISTRATION',terms_version:clean(body.terms_version,80)||'v1.0',status:'accepted',accepted_at:now(),user_agent:req.headers.get('user-agent')});await admin.from('am_registration_applications').update({consent_status:'accepted',updated_at:now()}).eq('id',a.id);const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:a.id});return json({ok:true,gate:g})}
  if(action==='upload_document'){
   const ru=await rate(admin,th,'registration_document_upload',20,3600);if(!ru?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:ru?.retry_after_seconds||60},429);
   const code=clean(body.document_type_code,100),filename=clean(body.filename,220)||'document.bin',mime=clean(body.mime_type,120),b64=String(body.data_base64||'');if(!b64)return json({error:'MISSING_FILE_DATA'},400);const {data:dt}=await admin.from('am_document_type_registry').select('*').eq('code',code).eq('is_active',true).maybeSingle();if(!dt)return json({error:'DOCUMENT_TYPE_NOT_FOUND'},404);if(!(dt.allowed_mime_types||[]).includes(mime))return json({error:'FILE_TYPE_NOT_ALLOWED'},400);let raw:string;try{raw=atob(b64)}catch{return json({error:'INVALID_FILE_DATA'},400)}const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(!bytes.length)return json({error:'MISSING_FILE_DATA'},400);if(bytes.length>Number(dt.max_file_mb||10)*1024*1024)return json({error:'FILE_TOO_LARGE'},413);const safe=filename.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${a.id}/${code}/${Date.now()}-${safe}`;const up=await admin.storage.from('candidate-registration-documents').upload(path,bytes,{contentType:mime,upsert:false});if(up.error)throw up.error;const {data:prev}=await admin.from('am_application_documents').select('id,version_no').eq('application_id',a.id).eq('document_type_id',dt.id).order('version_no',{ascending:false}).limit(1).maybeSingle();if(prev?.id)await admin.from('am_application_documents').update({verification_status:'superseded'}).eq('id',prev.id);const v=Number(prev?.version_no||0)+1;const ins=await admin.from('am_application_documents').insert({application_id:a.id,document_type_id:dt.id,version_no:v,storage_path:path,original_filename:filename,mime_type:mime,file_size:bytes.length,document_number:clean(body.document_number,120)||null,issued_at:body.issued_at||null,expires_at:body.expires_at||null,verification_status:dt.requires_verification?'pending':'verified',replaced_document_id:prev?.id||null}).select().single();if(ins.error)throw ins.error;const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:a.id});return json({ok:true,document:ins.data,gate:g})
  }
  if(action==='submit_payment_reference'){
   const rp=await rate(admin,th,'registration_payment_reference',10,3600);if(!rp?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rp?.retry_after_seconds||60},429);
   const ext=clean(body.external_reference,200)||null;const claimedAmount=body.amount==null?null:Number(body.amount);const claimedCurrency=clean(body.currency,10)||null;
   const r=await admin.from('am_registration_payment_refs').insert({application_id:a.id,payment_source:'manual_reference',external_reference:ext,amount:null,currency:null,status:'pending',metadata:{trust_level:'client_claim_unverified',client_claimed_amount:Number.isFinite(claimedAmount)?claimedAmount:null,client_claimed_currency:claimedCurrency}}).select().single();if(r.error)throw r.error;return json({ok:true,payment:r.data})
  }
  return json({error:'INVALID_ACTION'},400)
 }catch(e){console.error('registration-public-api',e);return json({error:'SERVER_ERROR'},500)}});