import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const enc=new TextEncoder();const now=()=>new Date().toISOString();const clean=(v:any,n=500)=>String(v??'').trim().slice(0,n);
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function sha(s:string){const h=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function code(n=6){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',b=new Uint8Array(n);crypto.getRandomValues(b);return [...b].map(x=>chars[x%chars.length]).join('')}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
 try{const auth=req.headers.get('authorization')||'',token=auth.startsWith('Bearer ')?auth.slice(7).trim():'';if(!token)return json({error:'UNAUTHORIZED'},401);const th=await sha(token);
  const {data:ss}=await admin.from('staff_sessions').select('id,user_id,expires_at,revoked_at').eq('token_hash',th).maybeSingle();if(!ss||ss.revoked_at||new Date(ss.expires_at).getTime()<=Date.now())return json({error:'SESSION_EXPIRED'},401);
  const {data:st}=await admin.from('staff_accounts').select('user_id,is_active').eq('user_id',ss.user_id).maybeSingle();if(!st?.is_active)return json({error:'FORBIDDEN'},403);
  const {data:pp}=await admin.from('staff_permissions').select('permission_code').eq('user_id',st.user_id).eq('is_allowed',true);const p=new Set((pp||[]).map((x:any)=>x.permission_code));
  const body=await req.json(),action=clean(body.action,80);
  const readActions=new Set(['dashboard','list_applications','list_document_config','list_institutions','list_batches']);
  const manageActions=new Set(['approve_invite','verify_document','activate','save_document_type','save_document_rule','create_batch','add_batch_trainees']);
  const canRead=p.has('registration.read')||p.has('registration.manage');
  if(readActions.has(action)&&!canRead)return json({error:'FORBIDDEN'},403);
  if(manageActions.has(action)&&!p.has('registration.manage'))return json({error:'FORBIDDEN'},403);
  if(action==='confirm_payment'&&!p.has('registration.payment.confirm'))return json({error:'FORBIDDEN'},403);
  await admin.from('staff_sessions').update({last_seen_at:now()}).eq('id',ss.id);
  if(action==='dashboard'){const [a,r,b,d,o]=await Promise.all([admin.from('am_registration_applications').select('*',{count:'exact',head:true}),admin.from('am_registration_applications').select('*',{count:'exact',head:true}).eq('activation_eligible',true).is('candidate_id',null),admin.from('am_institution_batches').select('*',{count:'exact',head:true}),admin.from('am_application_documents').select('*',{count:'exact',head:true}).eq('verification_status','pending'),admin.from('am_registration_delivery_outbox').select('*',{count:'exact',head:true}).eq('status','pending')]);return json({stats:{applications:a.count||0,ready_to_activate:r.count||0,batches:b.count||0,pending_documents:d.count||0,pending_delivery:o.count||0}})}
  if(action==='list_applications'){const {data,error}=await admin.from('am_registration_applications').select('*,am_institutions(name),am_institution_batches(name,batch_code)').order('created_at',{ascending:false}).limit(500);if(error)throw error;return json({applications:data||[]})}
  if(action==='approve_invite'){const id=clean(body.application_id,80),channel=clean(body.channel,20);const {data:a}=await admin.from('am_registration_applications').select('*').eq('id',id).single();if(!a)return json({error:'NOT_FOUND'},404);const dest=channel==='sms'?a.mobile:a.email;if(!dest)return json({error:'DESTINATION_MISSING'},400);const c=code(),h=await sha(c),exp=new Date(Date.now()+48*3600*1000).toISOString();await admin.from('am_registration_activation_codes').update({revoked_at:now()}).eq('application_id',id).is('revoked_at',null);const ins=await admin.from('am_registration_activation_codes').insert({application_id:id,channel,code_hash:h,expires_at:exp,created_by:st.user_id}).select().single();if(ins.error)throw ins.error;await admin.from('am_registration_delivery_outbox').insert({application_id:id,activation_code_id:ins.data.id,channel,recipient:dest,template_code:'registration_activation',payload:{application_number:a.application_number,code:c,expires_at:exp}});await admin.from('am_registration_applications').update({lifecycle_status:'invited',approved_at:now(),approved_by:st.user_id,updated_at:now()}).eq('id',id);return json({ok:true,application_number:a.application_number,activation_code:c,expires_at:exp,delivery_status:'queued'})}
  if(action==='confirm_payment'){const id=clean(body.application_id,80);await admin.from('am_registration_applications').update({payment_status:'confirmed',updated_at:now()}).eq('id',id);await admin.from('am_registration_payment_refs').insert({application_id:id,payment_source:'admin_confirmation',status:'confirmed',confirmed_at:now(),confirmed_by:st.user_id});const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:id});return json({ok:true,gate:g})}
  if(action==='verify_document'){const id=clean(body.document_id,80),status=clean(body.status,20);if(!['verified','rejected'].includes(status))return json({error:'INVALID_STATUS'},400);const {data:d}=await admin.from('am_application_documents').update({verification_status:status,rejection_reason:status==='rejected'?clean(body.reason,800):null,verified_at:status==='verified'?now():null,verified_by:st.user_id}).eq('id',id).select().single();if(!d)return json({error:'NOT_FOUND'},404);const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:d.application_id});return json({ok:true,gate:g})}
  if(action==='activate'){const id=clean(body.application_id,80);const {data:g}=await admin.rpc('am_recalculate_registration_gate',{p_application_id:id});if(!g?.eligible)return json({error:'NOT_ELIGIBLE',gate:g},409);const {data:c,error}=await admin.rpc('am_activate_registration_application',{p_application_id:id,p_actor:st.user_id});if(error)throw error;return json({ok:true,candidate_id:c})}
  if(action==='list_document_config'){const [{data:t},{data:r}]=await Promise.all([admin.from('am_document_type_registry').select('*').order('name'),admin.from('am_document_requirement_rules').select('*,am_document_type_registry(code,name)').order('priority')]);return json({types:t||[],rules:r||[]})}
  if(action==='save_document_type'){const x=body.document_type||{},payload={code:clean(x.code,100).toUpperCase(),name:clean(x.name,200),description:clean(x.description,1000)||null,requires_expiry:!!x.requires_expiry,requires_verification:x.requires_verification!==false,max_file_mb:Number(x.max_file_mb||10),is_active:x.is_active!==false,updated_at:now()};const r=x.id?await admin.from('am_document_type_registry').update(payload).eq('id',x.id).select().single():await admin.from('am_document_type_registry').insert(payload).select().single();if(r.error)throw r.error;return json({ok:true,item:r.data})}
  if(action==='save_document_rule'){const x=body.rule||{},payload={document_type_id:x.document_type_id,rule_name:clean(x.rule_name,200),scope_type:clean(x.scope_type,40),scope_text:clean(x.scope_text,120)||null,scope_uuid:x.scope_uuid||null,mandatory:x.mandatory!==false,blocking:x.blocking!==false,priority:Number(x.priority||100),is_active:x.is_active!==false,updated_at:now()};const r=x.id?await admin.from('am_document_requirement_rules').update(payload).eq('id',x.id).select().single():await admin.from('am_document_requirement_rules').insert(payload).select().single();if(r.error)throw r.error;return json({ok:true,item:r.data})}
  if(action==='list_institutions'){const {data}=await admin.from('am_institutions').select('*').order('name');return json({institutions:data||[]})}
  if(action==='list_batches'){const {data}=await admin.from('am_institution_batches').select('*,am_institutions(name)').order('created_at',{ascending:false});return json({batches:data||[]})}
  if(action==='create_batch'){const institution_id=clean(body.institution_id,80),name=clean(body.name,220);let batch_code='GRP-'+code();const r=await admin.from('am_institution_batches').insert({institution_id,batch_code,name,program_code:clean(body.program_code,100)||null,status:'approved',contract_payment_status:body.contract_payment_status==='confirmed'?'confirmed':'pending'}).select().single();if(r.error)throw r.error;return json({ok:true,batch:r.data})}
  if(action==='add_batch_trainees'){const batch_id=clean(body.batch_id,80),rows=Array.isArray(body.trainees)?body.trainees:[];const {data:b}=await admin.from('am_institution_batches').select('*').eq('id',batch_id).single();if(!b)return json({error:'BATCH_NOT_FOUND'},404);const made=[];for(let i=0;i<rows.length;i++){const t=rows[i];if(!clean(t.full_name,220))continue;const ai=await admin.from('am_registration_applications').insert({intake_type:'institution_bulk',institution_id:b.institution_id,batch_id:b.id,full_name:clean(t.full_name,220),email:clean(t.email,220)||null,mobile:clean(t.mobile,80)||null,date_of_birth:t.date_of_birth||null,source_code:'institution_bulk',program_code:b.program_code,lifecycle_status:'approved',payment_required:b.contract_payment_status!=='confirmed',payment_status:b.contract_payment_status==='confirmed'?'confirmed':'pending'}).select().single();if(ai.error)throw ai.error;await admin.from('am_batch_trainees').insert({batch_id:b.id,application_id:ai.data.id,seat_no:i+1});made.push({application_number:ai.data.application_number,full_name:ai.data.full_name})}return json({ok:true,batch_code:b.batch_code,created:made})}
  return json({error:'INVALID_ACTION'},400)
 }catch(e){return json({error:'SERVER_ERROR',detail:String((e as any)?.message||e)},500)}});