import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type, apikey','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const enc=new TextEncoder();
const hex=(a:Uint8Array)=>[...a].map(b=>b.toString(16).padStart(2,'0')).join('');
const sha=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))));
const clean=(v:any,max=4000)=>String(v??'').trim().slice(0,max);
const now=()=>new Date().toISOString();
const REF_BASE=(Deno.env.get('KAM_REFERENCE_BASE_URL')||'https://tamereltaher-svg.github.io/aviation-matrix-360/assets/kam-character-lock').replace(/\/$/,'');
const QC_THRESHOLD=Math.max(90,Math.min(100,Number(Deno.env.get('KAM_IDENTITY_QC_THRESHOLD')||96)));

async function authStaff(req:Request,admin:any){
 const a=req.headers.get('authorization')||'',t=a.startsWith('Bearer ')?a.slice(7).trim():''; if(!t)return null;
 const h=await sha(t); const {data:s}=await admin.from('staff_sessions').select('id,user_id,expires_at,revoked_at').eq('token_hash',h).maybeSingle();
 if(!s||s.revoked_at||new Date(s.expires_at).getTime()<=Date.now())return null;
 const {data:st}=await admin.from('staff_accounts').select('user_id,is_active,role_code').eq('user_id',s.user_id).maybeSingle(); if(!st?.is_active)return null;
 const {data:p}=await admin.from('staff_permissions').select('permission_code').eq('user_id',s.user_id).eq('permission_code','kids.manage').eq('is_allowed',true).maybeSingle();
 if(!p&&st.role_code!=='super_admin')return null;
 await admin.from('staff_sessions').update({last_seen_at:now()}).eq('id',s.id); return s;
}
function extractText(resp:any){if(resp?.output_text)return resp.output_text;for(const item of resp?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c?.text)return c.text;return '';}

const missionSchema={type:'object',additionalProperties:false,required:['title','big_question','learning_goal','knowledge_goal','learning_objectives','key_concepts','vocabulary','primary_skill','primary_value','aviation_connection','difficulty','stamp_name','pages'],properties:{title:{type:'string'},big_question:{type:'string'},learning_goal:{type:'string'},knowledge_goal:{type:'string'},learning_objectives:{type:'array',items:{type:'string'},minItems:2,maxItems:6},key_concepts:{type:'array',items:{type:'string'},minItems:2,maxItems:8},vocabulary:{type:'array',items:{type:'string'},minItems:3,maxItems:12},primary_skill:{type:'string'},primary_value:{type:'string'},aviation_connection:{type:'string'},difficulty:{type:'string'},stamp_name:{type:'string'},pages:{type:'array',minItems:10,maxItems:10,items:{type:'object',additionalProperties:false,required:['page_no','scene_title','narration','dialogue','learning_purpose','character_codes','production_notes','artwork'],properties:{page_no:{type:'integer',minimum:1,maximum:10},scene_title:{type:'string'},narration:{type:'string'},dialogue:{type:'string'},learning_purpose:{type:'string'},character_codes:{type:'array',items:{type:'string'},maxItems:4},production_notes:{type:'string'},artwork:{type:'object',additionalProperties:false,required:['scene_brief','background_brief','asset_requirements','text_safe_area','illustration_notes','image_prompt'],properties:{scene_brief:{type:'string'},background_brief:{type:'string'},asset_requirements:{type:'string'},text_safe_area:{type:'string'},illustration_notes:{type:'string'},image_prompt:{type:'string'}}}}}}}};

const qcSchema={type:'object',additionalProperties:false,required:['overall_pass','overall_score','summary','characters'],properties:{overall_pass:{type:'boolean'},overall_score:{type:'number',minimum:0,maximum:100},summary:{type:'string'},characters:{type:'array',minItems:1,maxItems:4,items:{type:'object',additionalProperties:false,required:['character_code','face_score','hair_score','age_score','proportion_score','outfit_score','accessory_score','overall_score','pass','differences','regeneration_instructions'],properties:{character_code:{type:'string'},face_score:{type:'number',minimum:0,maximum:100},hair_score:{type:'number',minimum:0,maximum:100},age_score:{type:'number',minimum:0,maximum:100},proportion_score:{type:'number',minimum:0,maximum:100},outfit_score:{type:'number',minimum:0,maximum:100},accessory_score:{type:'number',minimum:0,maximum:100},overall_score:{type:'number',minimum:0,maximum:100},pass:{type:'boolean'},differences:{type:'array',items:{type:'string'},maxItems:10},regeneration_instructions:{type:'array',items:{type:'string'},maxItems:10}}}}}};

async function buildContext(admin:any,missionId:string){
 const {data:m,error}=await admin.from('kids_missions').select('id,code,name,title,big_question,learning_goal,mission_no,season_id,kids_seasons(id,code,name,learning_stage,base_goal,depth_goal,level_id,kids_levels(id,code,name,age_range,min_age,max_age,learning_stage,primary_goal,learner_outcome))').eq('id',missionId).single(); if(error)throw error;
 const [{data:bp},{data:lm},{data:sp},{data:ap},{data:rules},{data:acc},{data:chars},{data:appear}]=await Promise.all([
  admin.from('kids_mission_blueprints').select('*').eq('mission_id',missionId).maybeSingle(),admin.from('kids_learning_matrix').select('*').eq('mission_id',missionId).maybeSingle(),admin.from('kids_script_pages').select('page_no,page_role,page_objective,scene_title,narration,dialogue,learning_purpose,character_codes,production_notes').eq('mission_id',missionId).order('page_no'),admin.from('kids_artwork_pages').select('page_no,page_role,artwork_objective,scene_brief,background_brief,asset_requirements,text_safe_area,illustration_notes,character_rule,background,text_area,asset_path,status').eq('mission_id',missionId).order('page_no'),admin.from('kids_content_rulebook').select('category,rule_text,priority').eq('status','active').order('priority'),admin.from('kids_aviation_accuracy_master').select('domain,topic,approved_definition').eq('status','Approved'),admin.from('kids_characters').select('id,code,name,role_title,description,personality,values,tier,usage_rule,primary_image_path,profile_image_path').eq('is_active',true).order('sort_order'),admin.from('kids_character_appearance_control').select('character_code,character_name,appearance_rule,status').order('character_name')
 ]);
 return {mission:m,blueprint:bp,learning_matrix:lm,script_pages:sp||[],artwork_pages:ap||[],rules:rules||[],aviation_accuracy:acc||[],characters:chars||[],appearance_rules:appear||[]};
}
async function getLocks(admin:any,codes:string[]){
 if(!codes.length)return {readiness:[],policies:[],rules:[],assets:[]};
 const [{data:readiness,error:re},{data:policies,error:pe},{data:rules,error:rue},{data:assets,error:ae}]=await Promise.all([
  admin.from('kids_character_lock_readiness').select('*').in('character_code',codes),admin.from('kids_character_lock_policies').select('*').in('character_code',codes).eq('is_active',true),admin.from('kids_character_visual_rules').select('character_code,rule_category,rule_text,strictness,sort_order').in('character_code',codes).eq('is_active',true).order('sort_order'),admin.from('kids_character_reference_assets').select('character_code,asset_type,asset_role,source_file_name,approval_status,is_canonical').in('character_code',codes).eq('is_canonical',true)
 ]); if(re||pe||rue||ae)throw re||pe||rue||ae; return {readiness:readiness||[],policies:policies||[],rules:rules||[],assets:assets||[]};
}
function assertLockReady(codes:string[],bundle:any){for(const c of codes){const r=bundle.readiness.find((x:any)=>x.character_code===c);if(!r||r.lock_status!=='LOCK_READY')throw Object.assign(new Error('CHARACTER_LOCK_NOT_READY:'+c),{httpStatus:409});}}
async function fetchRefBlob(code:string,type:'full'|'face'){
 const name=type==='full'?'01_FULL_BODY_CANONICAL.jpg':'02_FACE_CANONICAL.jpg'; const url=`${REF_BASE}/${encodeURIComponent(code)}/${name}`; const r=await fetch(url); if(!r.ok)throw Object.assign(new Error(`CHARACTER_REFERENCE_ASSET_MISSING:${code}:${type}`),{httpStatus:409}); return {blob:await r.blob(),url,name};
}
async function runIdentityQC(openaiKey:string,model:string,selected:string[],generatedB64:string,refs:any[]){
 const content:any[]=[{type:'input_text',text:`You are a strict visual identity quality-control inspector for Kids Aviation Matrix 360. Compare the GENERATED SCENE against the canonical reference images for each character. Score only identity consistency: face geometry, eyes, hair shape/color, age appearance, body proportions, outfit design/colors, and signature accessories. Ignore pose, facial expression, camera angle, lighting and background because those may vary. Be conservative. A character passes only if every identity category is visually consistent and overall_score is at least ${QC_THRESHOLD}. Set overall_pass true only if every listed character passes and overall_score is at least ${QC_THRESHOLD}. Return precise differences and concise regeneration instructions.`},{type:'input_text',text:`Selected character codes: ${JSON.stringify(selected)}. First image is GENERATED SCENE. Following images are canonical references labeled in text order.`},{type:'input_image',image_url:`data:image/png;base64,${generatedB64}`,detail:'high'}];
 for(const rr of refs){content.push({type:'input_text',text:`Canonical reference: ${rr.code} ${rr.type}`});content.push({type:'input_image',image_url:rr.url,detail:'high'});}
 const body:any={model,input:[{role:'user',content}],text:{format:{type:'json_schema',name:'kam_character_identity_qc',strict:true,schema:qcSchema}},store:false};
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+openaiKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error('OPENAI_IDENTITY_QC:'+JSON.stringify(d));let qc:any;try{qc=JSON.parse(extractText(d))}catch{throw new Error('IDENTITY_QC_JSON_PARSE_FAILED')}
 for(const c of qc.characters||[]){c.pass=Boolean(c.pass&&Number(c.overall_score)>=QC_THRESHOLD&&Number(c.face_score)>=QC_THRESHOLD&&Number(c.hair_score)>=QC_THRESHOLD&&Number(c.age_score)>=QC_THRESHOLD&&Number(c.proportion_score)>=QC_THRESHOLD&&Number(c.outfit_score)>=QC_THRESHOLD&&Number(c.accessory_score)>=QC_THRESHOLD)}
 qc.overall_pass=Boolean((qc.characters||[]).length===selected.length&&(qc.characters||[]).every((c:any)=>c.pass)&&Number(qc.overall_score)>=QC_THRESHOLD);qc.threshold=QC_THRESHOLD;return qc;
}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
 try{
  const staff=await authStaff(req,admin); if(!staff)return json({error:'UNAUTHORIZED'},401); const b=await req.json(); const action=clean(b.action,60); const openaiKey=Deno.env.get('OPENAI_API_KEY')||'';
  if(action==='refs'){
   const [{data:levels},{data:seasons},{data:missions},{data:characters},{data:locks}]=await Promise.all([admin.from('kids_levels').select('id,code,name,age_range,learning_stage,sort_order').eq('is_active',true).order('sort_order'),admin.from('kids_seasons').select('id,level_id,code,name,sort_order').eq('is_active',true).order('sort_order'),admin.from('kids_missions').select('id,season_id,code,name,title,mission_no,sort_order,production_status').eq('is_active',true).order('sort_order'),admin.from('kids_characters').select('id,code,name,role_title,personality,values,tier,usage_rule,primary_image_path,profile_image_path').eq('is_active',true).order('sort_order'),admin.from('kids_character_lock_readiness').select('character_code,character_name,active_lock_rules,canonical_reference_count,lock_status').order('character_name')]);
   return json({openai_configured:!!openaiKey,text_model:Deno.env.get('OPENAI_TEXT_MODEL')||'gpt-5.4',image_model:Deno.env.get('OPENAI_IMAGE_MODEL')||'gpt-image-2',identity_qc_model:Deno.env.get('OPENAI_IDENTITY_QC_MODEL')||Deno.env.get('OPENAI_TEXT_MODEL')||'gpt-5.4',identity_qc_threshold:QC_THRESHOLD,identity_lock_enabled:true,reference_base_url:REF_BASE,levels:levels||[],seasons:seasons||[],missions:missions||[],characters:characters||[],character_locks:locks||[]});
  }
  if(action==='mission_context'){const missionId=clean(b.mission_id,80);if(!missionId)return json({error:'MISSION_REQUIRED'},400);return json(await buildContext(admin,missionId));}
  if(action==='generate_mission'){
   if(!openaiKey)return json({error:'OPENAI_NOT_CONFIGURED'},503); const missionId=clean(b.mission_id,80),brief=clean(b.brief,8000),selected=Array.isArray(b.character_codes)?b.character_codes.map((x:any)=>clean(x,30)).filter(Boolean):[]; if(!missionId)return json({error:'MISSION_REQUIRED'},400);
   const ctx=await buildContext(admin,missionId),locks=await getLocks(admin,selected); if(selected.length)assertLockReady(selected,locks); const level=(ctx.mission as any)?.kids_seasons?.kids_levels||{};
   const prompt=`You are the KAM AI Production Studio for Kids Aviation Matrix 360. Create an editorial DRAFT only. MISSION CONTEXT:${JSON.stringify(ctx.mission)} BLUEPRINT:${JSON.stringify(ctx.blueprint)} LEARNING MATRIX:${JSON.stringify(ctx.learning_matrix)} EXISTING PAGE ROLES:${JSON.stringify(ctx.script_pages.map((x:any)=>({page_no:x.page_no,page_role:x.page_role,page_objective:x.page_objective})))} CONTENT RULEBOOK:${JSON.stringify(ctx.rules)} AVIATION ACCURACY MASTER:${JSON.stringify(ctx.aviation_accuracy)} CHARACTERS:${JSON.stringify(ctx.characters)} APPEARANCE RULES:${JSON.stringify(ctx.appearance_rules)} CHARACTER LOCK RULES:${JSON.stringify(locks.rules)} SELECTED CHARACTERS:${JSON.stringify(selected)} USER BRIEF:${brief||'Improve and fully develop this mission using the existing mission intent.'} Requirements: age appropriate for ${level.age_range||'the selected level'}; exactly 10 pages; preserve KAM learning progression; no unsupported technical facts; artwork prompts must explicitly say selected characters are identity-locked to canonical references and may vary only in pose, expression, camera angle and background; no embedded text. Return structured JSON only.`;
   const body:any={model:Deno.env.get('OPENAI_TEXT_MODEL')||'gpt-5.4',input:[{role:'user',content:[{type:'input_text',text:prompt}]}],text:{format:{type:'json_schema',name:'kam_mission_draft',strict:true,schema:missionSchema}},store:false}; const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+openaiKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error('OPENAI_TEXT:'+JSON.stringify(d));let payload:any;try{payload=JSON.parse(extractText(d))}catch{throw new Error('OPENAI_JSON_PARSE_FAILED')}
   const {data:proj,error:pe}=await admin.from('kids_ai_projects').insert({mission_id:missionId,title:payload.title,brief,selected_character_codes:selected,status:'generated',ai_payload:payload,created_by:staff.user_id}).select().single();if(pe)throw pe;await admin.from('kids_ai_generations').insert({project_id:proj.id,mission_id:missionId,generation_type:'mission_draft',model_name:d.model||body.model,prompt:brief,response_payload:{draft:payload,identity_lock:selected.length?true:false,character_codes:selected},status:'generated',created_by:staff.user_id});return json({ok:true,project:proj,draft:payload,model:d.model||body.model});
  }
  if(action==='apply_draft'){
   const projectId=clean(b.project_id,80);if(!projectId)return json({error:'PROJECT_REQUIRED'},400);const {data:p,error}=await admin.from('kids_ai_projects').select('*').eq('id',projectId).single();if(error)throw error;const {data:rpc,error:re}=await admin.rpc('kids_apply_ai_mission_draft',{p_mission_id:p.mission_id,p_payload:p.ai_payload});if(re)throw re;await admin.from('kids_ai_projects').update({status:'review',updated_at:now()}).eq('id',projectId);await admin.from('kids_ai_generations').update({status:'applied'}).eq('project_id',projectId).eq('generation_type','mission_draft');return json({ok:true,result:rpc});
  }
  if(action==='generate_image'){
   if(!openaiKey)return json({error:'OPENAI_NOT_CONFIGURED'},503);const missionId=clean(b.mission_id,80),projectId=clean(b.project_id,80)||null,pageNo=Math.max(1,Math.min(10,Number(b.page_no||1)));if(!missionId)return json({error:'MISSION_REQUIRED'},400); const selected=Array.isArray(b.character_codes)?b.character_codes.map((x:any)=>clean(x,30)).filter(Boolean):[];if(!selected.length)return json({error:'CHARACTER_REQUIRED_FOR_LOCKED_GENERATION'},400);
   const locks=await getLocks(admin,selected);assertLockReady(selected,locks);const ctx=await buildContext(admin,missionId),art=(ctx.artwork_pages||[]).find((x:any)=>x.page_no===pageNo)||{},script=(ctx.script_pages||[]).find((x:any)=>x.page_no===pageNo)||{},characterInfo=(ctx.characters||[]).filter((x:any)=>selected.includes(x.code)),appearance=(ctx.appearance_rules||[]).filter((x:any)=>selected.includes(x.character_code));
   const refs:any[]=[];for(const code of selected){refs.push({code,type:'full',...(await fetchRefBlob(code,'full'))});refs.push({code,type:'face',...(await fetchRefBlob(code,'face'))});}
   const extra=clean(b.prompt,5000);const imagePrompt=`Create one premium children's aviation illustration for Kids Aviation Matrix 360 using the supplied canonical character reference images as strict identity anchors. Identity fidelity has absolute priority over artistic variation. Do NOT redesign, beautify, age, de-age, restyle or reinterpret any selected character. Preserve face geometry, eye shape/color, eyebrow shape, nose/mouth proportions, hair silhouette/style/color/length, age appearance, body proportions, outfit construction/colors, shoes and signature accessories exactly from canonical references. Allowed variation only: pose, facial expression, camera angle, lighting and background. If scene composition conflicts with identity fidelity, simplify the scene rather than changing a character. STYLE: Cartoon Premium Aviation matching canonical references; polished children's editorial illustration; bright but elegant; professional airport details; friendly; cinematic soft lighting; clean composition; NO WRITTEN TEXT. MISSION:${(ctx.mission as any)?.title||(ctx.mission as any)?.name}. PAGE:${pageNo}. PAGE ROLE:${script.page_role||''}. SCENE:${art.scene_brief||script.scene_title||''}. BACKGROUND:${art.background_brief||art.background||''}. NARRATIVE ACTION:${script.narration||''}. CHARACTERS:${JSON.stringify(characterInfo)}. LOCK RULES:${JSON.stringify(locks.rules)}. APPEARANCE RULES:${JSON.stringify(appearance)}. TEXT SAFE AREA:${art.text_safe_area||art.text_area||'leave clean negative space for later page text'}. EXTRA:${extra}.`;
   const model=Deno.env.get('OPENAI_IMAGE_MODEL')||'gpt-image-2';const form=new FormData();form.append('model',model);form.append('prompt',imagePrompt);form.append('size',clean(b.size,30)||'1536x1024');form.append('quality',clean(b.quality,20)||'high');form.append('n','1');for(const rr of refs)form.append('image[]',rr.blob,`${rr.code}_${rr.type}.jpg`);
   const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:'Bearer '+openaiKey},body:form});const d=await r.json();if(!r.ok)throw new Error('OPENAI_IMAGE_EDIT:'+JSON.stringify(d));const b64=d?.data?.[0]?.b64_json||d?.data?.[0]?.b64;if(!b64)throw new Error('IMAGE_DATA_MISSING');const raw=atob(b64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
   const qcModel=Deno.env.get('OPENAI_IDENTITY_QC_MODEL')||Deno.env.get('OPENAI_TEXT_MODEL')||'gpt-5.4';const qc=await runIdentityQC(openaiKey,qcModel,selected,b64,refs);
   const path=`missions/${missionId}/page-${String(pageNo).padStart(2,'0')}/${Date.now()}-locked.png`;const up=await admin.storage.from('kids-ai-studio').upload(path,bytes,{contentType:'image/png',upsert:false});if(up.error)throw up.error;
   const lockMeta={identity_lock:true,character_codes:selected,reference_urls:refs.map(x=>x.url),lock_rules_count:locks.rules.length,canonical_reference_count:locks.assets.length,identity_qc:qc,identity_qc_pass:qc.overall_pass,identity_qc_score:qc.overall_score,identity_qc_threshold:QC_THRESHOLD};const {data:g,error:ge}=await admin.from('kids_ai_generations').insert({project_id:projectId,mission_id:missionId,page_no:pageNo,generation_type:'image',model_name:model,prompt:imagePrompt,response_payload:{revised_prompt:d?.data?.[0]?.revised_prompt||null,...lockMeta},storage_bucket:'kids-ai-studio',storage_path:path,status:qc.overall_pass?'review':'identity_rejected',created_by:staff.user_id}).select().single();if(ge)throw ge;const {data:signed,error:se}=await admin.storage.from('kids-ai-studio').createSignedUrl(path,3600);if(se)throw se;return json({ok:true,generation:g,url:signed.signedUrl,expires_in:3600,lock:lockMeta,qc});
  }
  if(action==='verify_image'){
   if(!openaiKey)return json({error:'OPENAI_NOT_CONFIGURED'},503);const generationId=clean(b.generation_id,80);if(!generationId)return json({error:'GENERATION_REQUIRED'},400);const {data:g,error}=await admin.from('kids_ai_generations').select('*').eq('id',generationId).eq('generation_type','image').single();if(error)throw error;const selected=g.response_payload?.character_codes||[];if(!selected.length)return json({error:'CHARACTER_CODES_MISSING'},409);const refs:any[]=[];for(const code of selected){refs.push({code,type:'full',...(await fetchRefBlob(code,'full'))});refs.push({code,type:'face',...(await fetchRefBlob(code,'face'))});}const {data:file,error:de}=await admin.storage.from(g.storage_bucket||'kids-ai-studio').download(g.storage_path);if(de)throw de;const arr=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<arr.length;i+=0x8000)bin+=String.fromCharCode(...arr.subarray(i,i+0x8000));const b64=btoa(bin);const qc=await runIdentityQC(openaiKey,Deno.env.get('OPENAI_IDENTITY_QC_MODEL')||Deno.env.get('OPENAI_TEXT_MODEL')||'gpt-5.4',selected,b64,refs);await admin.from('kids_ai_generations').update({status:qc.overall_pass?'review':'identity_rejected',response_payload:{...(g.response_payload||{}),identity_qc:qc,identity_qc_pass:qc.overall_pass,identity_qc_score:qc.overall_score,identity_qc_threshold:QC_THRESHOLD}}).eq('id',generationId);return json({ok:true,qc});
  }
  if(action==='approve_image'){
   const generationId=clean(b.generation_id,80);if(!generationId)return json({error:'GENERATION_REQUIRED'},400);const {data:g,error}=await admin.from('kids_ai_generations').select('*').eq('id',generationId).eq('generation_type','image').single();if(error)throw error;const rp=g.response_payload||{};if(rp.identity_lock!==true)return json({error:'UNLOCKED_IMAGE_CANNOT_BE_APPROVED'},409);if(rp.identity_qc_pass!==true||Number(rp.identity_qc_score)<QC_THRESHOLD)return json({error:'IDENTITY_QC_FAILED',detail:`Identity QC must pass at ${QC_THRESHOLD}% or above before approval. Current score: ${rp.identity_qc_score??'N/A'}`},409);await admin.from('kids_ai_generations').update({status:'approved',approved_at:now()}).eq('id',generationId);await admin.from('kids_artwork_pages').update({asset_path:g.storage_path,status:'AI Image Approved - Identity Locked + QC Passed',updated_at:now()}).eq('mission_id',g.mission_id).eq('page_no',g.page_no);await admin.from('kids_content_tracker').update({artwork_status:'In Review',overall_status:'In Production',updated_at:now()}).eq('mission_id',g.mission_id);return json({ok:true,identity_lock:true,identity_qc:true,score:rp.identity_qc_score,threshold:QC_THRESHOLD});
  }
  if(action==='character_lock_bundle'){const codes=Array.isArray(b.character_codes)?b.character_codes.map((x:any)=>clean(x,30)).filter(Boolean):[];const bundle=await getLocks(admin,codes);return json(bundle);}
  if(action==='list_projects'){const missionId=clean(b.mission_id,80);let q=admin.from('kids_ai_projects').select('id,mission_id,title,brief,selected_character_codes,status,created_at,updated_at').order('created_at',{ascending:false}).limit(30);if(missionId)q=q.eq('mission_id',missionId);const {data,error}=await q;if(error)throw error;return json({items:data||[]});}
  return json({error:'INVALID_ACTION'},400);
 }catch(e){console.error(e);const s=Number((e as any)?.httpStatus||500);return json({error:s===409?'CHARACTER_IDENTITY_LOCK_ERROR':'SERVER_ERROR',detail:String((e as any)?.message||e)},s)}
});