import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const enc=new TextEncoder();
function b64urlToBytes(s:string){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function bytesToB64url(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256Hex(s:string){return bytesToHex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
async function verifyPbkdf2(password:string,stored:string){const [kind,iterS,saltS,hashS]=stored.split('$');if(kind!=='pbkdf2_sha256'||!iterS||!saltS||!hashS)return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64urlToBytes(saltS),iterations:Number(iterS)},key,256);const got=new Uint8Array(bits),want=b64urlToBytes(hashS);if(got.length!==want.length)return false;let diff=0;for(let i=0;i<got.length;i++)diff|=got[i]^want[i];return diff===0}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return bytesToB64url(b)}
const clean=(v:any,max=500)=>String(v??'').trim().slice(0,max);
const now=()=>new Date().toISOString();

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
 const url=Deno.env.get('SUPABASE_URL')!; const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 try{
  const body=await req.json(); const action=clean(body.action,60);
  if(action==='login'){
   const email=clean(body.email,200).toLowerCase(),password=String(body.password||''); if(!email||!password)return json({error:'INVALID_CREDENTIALS'},401);
   const {data:guard}=await admin.from('staff_login_guard').select('*').eq('email',email).maybeSingle();
   if(guard?.locked_until&&new Date(guard.locked_until).getTime()>Date.now())return json({error:'TOO_MANY_ATTEMPTS'},429);
   const {data:staff}=await admin.from('staff_accounts').select('user_id,email,full_name,role_code,is_active,password_hash').eq('email',email).maybeSingle();
   let ok=false;if(staff?.is_active&&staff?.password_hash)ok=await verifyPbkdf2(password,staff.password_hash);
   if(!ok){const t=Date.now(),fresh=!guard||t-new Date(guard.window_started_at).getTime()>15*60*1000,count=fresh?1:Number(guard.failed_count||0)+1,locked=count>=5?new Date(t+15*60*1000).toISOString():null;await admin.from('staff_login_guard').upsert({email,failed_count:count,window_started_at:fresh?new Date(t).toISOString():guard.window_started_at,locked_until:locked,updated_at:new Date(t).toISOString()},{onConflict:'email'});return json({error:locked?'TOO_MANY_ATTEMPTS':'INVALID_CREDENTIALS'},locked?429:401)}
   const {data:perms}=await admin.from('staff_permissions').select('permission_code').eq('user_id',staff.user_id).eq('is_allowed',true).limit(1); if(!perms?.length)return json({error:'FORBIDDEN'},403);
   await admin.from('staff_login_guard').upsert({email,failed_count:0,window_started_at:now(),locked_until:null,updated_at:now()},{onConflict:'email'});
   const token=randomToken(),tokenHash=await sha256Hex(token),expiresAt=new Date(Date.now()+12*60*60*1000).toISOString();
   await admin.from('staff_sessions').insert({user_id:staff.user_id,token_hash:tokenHash,expires_at:expiresAt,user_agent:req.headers.get('user-agent')||null}); await admin.from('staff_accounts').update({last_login_at:now()}).eq('user_id',staff.user_id);
   return json({ok:true,token,expires_at:expiresAt,staff:{email:staff.email,full_name:staff.full_name,role_code:staff.role_code}});
  }
  const auth=req.headers.get('authorization')||'',token=auth.startsWith('Bearer ')?auth.slice(7).trim():''; if(!token)return json({error:'UNAUTHORIZED'},401);
  const tokenHash=await sha256Hex(token); const {data:session}=await admin.from('staff_sessions').select('id,user_id,expires_at,revoked_at').eq('token_hash',tokenHash).maybeSingle();
  if(!session||session.revoked_at||new Date(session.expires_at).getTime()<=Date.now())return json({error:'SESSION_EXPIRED'},401);
  const {data:staff}=await admin.from('staff_accounts').select('user_id,email,full_name,role_code,is_active').eq('user_id',session.user_id).maybeSingle(); if(!staff?.is_active)return json({error:'FORBIDDEN'},403);
  const {data:perms}=await admin.from('staff_permissions').select('permission_code').eq('user_id',staff.user_id).eq('is_allowed',true); const permissionSet=new Set((perms||[]).map((x:any)=>x.permission_code));
  await admin.from('staff_sessions').update({last_seen_at:now()}).eq('id',session.id);
  if(action==='logout'){await admin.from('staff_sessions').update({revoked_at:now()}).eq('id',session.id);return json({ok:true})}
  if(action==='me')return json({ok:true,staff,permissions:[...permissionSet]});

  const has=(p:string)=>permissionSet.has(p);
  const commercialRead=()=>has('store.view')||has('store.manage');
  const readAllowed:Record<string,()=>boolean>={
   dashboard:()=>commercialRead(),
   list_products:()=>commercialRead()||has('products.manage')||has('products.images.manage'),
   get_product:()=>commercialRead()||has('products.manage')||has('products.images.manage'),
   list_programs:()=>commercialRead()||has('programs.manage')||has('pricing.manage'),
   list_addons:()=>commercialRead()||has('pricing.manage')||has('programs.manage'),
   list_requests:()=>commercialRead()||has('gateway.manage')||has('quotations.manage'),
   get_request:()=>commercialRead()||has('gateway.manage')||has('quotations.manage'),
   list_quotations:()=>commercialRead()||has('quotations.manage'),
   get_quotation:()=>commercialRead()||has('quotations.manage'),
   list_institutions:()=>commercialRead()||has('institutions.manage'),
   get_institution_profile:()=>commercialRead()||has('institutions.manage'),
   list_meetings:()=>commercialRead()||has('meetings.manage')
  };
  const writePermission:Record<string,string>={
   save_product:'products.manage',delete_product:'products.manage',
   upload_image:'products.images.manage',set_primary_image:'products.images.manage',delete_image:'products.images.manage',
   save_program:'programs.manage',delete_program:'programs.manage',
   save_addon:'pricing.manage',delete_addon:'pricing.manage',
   update_request_status:'gateway.manage',
   create_quotation:'quotations.manage',save_quotation:'quotations.manage',send_quotation:'quotations.manage',mark_quotation_accepted:'quotations.manage',
   save_institution:'institutions.manage',
   update_meeting_status:'meetings.manage'
  };
  if(readAllowed[action]&&!readAllowed[action]())return json({error:'FORBIDDEN'},403);
  if(writePermission[action]&&!has(writePermission[action]))return json({error:'FORBIDDEN'},403);

  if(action==='dashboard'){
   const [products,activeProducts,programs,requests,openRequests,institutions,meetings,draftQuotes,sentQuotes,approved,execution]=await Promise.all([
    admin.from('store_products').select('*',{count:'exact',head:true}),admin.from('store_products').select('*',{count:'exact',head:true}).eq('is_active',true),admin.from('am_programs').select('*',{count:'exact',head:true}).eq('is_active',true),admin.from('am_requests').select('*',{count:'exact',head:true}),admin.from('am_requests').select('*',{count:'exact',head:true}).in('status',['new','reviewing','contacted','quotation_pending']),admin.from('am_institutions').select('*',{count:'exact',head:true}).neq('status','archived'),admin.from('am_meetings').select('*',{count:'exact',head:true}).in('status',['requested','scheduled']),admin.from('am_quotations').select('*',{count:'exact',head:true}).eq('status','draft'),admin.from('am_quotations').select('*',{count:'exact',head:true}).eq('status','sent'),admin.from('am_requests').select('*',{count:'exact',head:true}).eq('status','approved'),admin.from('am_requests').select('*',{count:'exact',head:true}).eq('status','execution')]);
   const [{data:recentRequests},{data:activeQuotes},{data:statusRows}]=await Promise.all([
    admin.from('am_requests').select('id,request_number,request_type,audience_code,status,contact_person,estimated_total,currency,created_at').order('created_at',{ascending:false}).limit(6),
    admin.from('am_quotations').select('total_amount,status').in('status',['sent','accepted']),
    admin.from('am_requests').select('status')]);
   const pipelineValue=(activeQuotes||[]).filter((q:any)=>q.status==='sent').reduce((s:number,q:any)=>s+Number(q.total_amount||0),0),acceptedValue=(activeQuotes||[]).filter((q:any)=>q.status==='accepted').reduce((s:number,q:any)=>s+Number(q.total_amount||0),0);
   const status_counts:any={};for(const r of statusRows||[])status_counts[r.status]=(status_counts[r.status]||0)+1;
   return json({stats:{products:products.count||0,active_products:activeProducts.count||0,programs:programs.count||0,requests:requests.count||0,open_requests:openRequests.count||0,institutions:institutions.count||0,meetings:meetings.count||0,draft_quotes:draftQuotes.count||0,sent_quotes:sentQuotes.count||0,approved:approved.count||0,execution:execution.count||0,pipeline_value:pipelineValue,accepted_value:acceptedValue},status_counts,recent_requests:recentRequests||[]});
  }

  if(action==='list_products'){const {data,error}=await admin.from('store_products').select('*').order('sort_order').order('name');if(error)throw error;return json({products:data||[]})}
  if(action==='get_product'){const id=clean(body.id,80);const [p,im,vr,op,au]=await Promise.all([admin.from('store_products').select('*').eq('id',id).single(),admin.from('store_product_images').select('*').eq('product_id',id).order('sort_order'),admin.from('store_product_variants').select('*').eq('product_id',id).order('sort_order'),admin.from('store_personalization_options').select('*').eq('product_id',id).order('sort_order'),admin.from('store_product_audiences').select('*').eq('product_id',id)]);if(p.error)throw p.error;return json({product:p.data,images:im.data||[],variants:vr.data||[],options:op.data||[],audiences:(au.data||[]).map((x:any)=>x.audience_code)})}
  if(action==='save_product'){const p=body.product||{};const payload={name:clean(p.name,200),sku:p.sku||null,slug:clean(p.slug,220),category:clean(p.category||'PRODUCT',80),short_description:p.short_description||null,description:p.description||null,base_price:Number(p.base_price||0),currency:clean(p.currency||'EGP',10),price_is_estimate:!!p.price_is_estimate,is_active:!!p.is_active,is_featured:!!p.is_featured,sort_order:Number(p.sort_order||999)};if(!payload.name||!payload.slug)return json({error:'NAME_AND_SLUG_REQUIRED'},400);let result=p.id?await admin.from('store_products').update(payload).eq('id',p.id).select().single():await admin.from('store_products').insert(payload).select().single();if(result.error)throw result.error;const id=result.data.id;await admin.from('store_product_audiences').delete().eq('product_id',id);const audiences=Array.isArray(body.audiences)?body.audiences:[];if(audiences.length){const r=await admin.from('store_product_audiences').insert(audiences.map((a:string)=>({product_id:id,audience_code:a})));if(r.error)throw r.error}await admin.from('store_product_variants').delete().eq('product_id',id);const variants=Array.isArray(body.variants)?body.variants:[];if(variants.length){const r=await admin.from('store_product_variants').insert(variants.filter((v:any)=>v.variant_type&&v.variant_value).map((v:any,i:number)=>({product_id:id,variant_type:v.variant_type,variant_value:v.variant_value,price_delta:Number(v.price_delta||0),sku_suffix:v.sku_suffix||null,is_active:v.is_active!==false,sort_order:i})));if(r.error)throw r.error}await admin.from('store_personalization_options').delete().eq('product_id',id);const options=Array.isArray(body.options)?body.options:[];if(options.length){const r=await admin.from('store_personalization_options').insert(options.filter((o:any)=>o.code&&o.label).map((o:any,i:number)=>({product_id:id,code:o.code,label:o.label,input_type:o.input_type==='file'?'image':o.input_type==='checkbox'?'boolean':(o.input_type||'text'),is_required:!!o.is_required,price_delta:Number(o.price_delta||0),config:o.config||{},sort_order:i,is_active:o.is_active!==false})));if(r.error)throw r.error}return json({ok:true,product:result.data})}
  if(action==='delete_product'){const id=clean(body.id,80);const {data:imgs}=await admin.from('store_product_images').select('storage_path').eq('product_id',id);const paths=(imgs||[]).map((x:any)=>x.storage_path);if(paths.length)await admin.storage.from('product-images').remove(paths);const {error}=await admin.from('store_products').delete().eq('id',id);if(error)throw error;return json({ok:true})}
  if(action==='upload_image'){const productId=clean(body.product_id,80),filename=clean(body.filename||'image.bin',200),contentType=clean(body.content_type||'application/octet-stream',80),dataB64=String(body.data_base64||'');if(!productId||!dataB64)return json({error:'MISSING_IMAGE_DATA'},400);const raw=atob(dataB64),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);if(bytes.length>5*1024*1024)return json({error:'IMAGE_TOO_LARGE'},413);const safe=filename.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${productId}/${Date.now()}-${safe}`;const up=await admin.storage.from('product-images').upload(path,bytes,{contentType,upsert:false});if(up.error)throw up.error;const {data:existing}=await admin.from('store_product_images').select('id').eq('product_id',productId).limit(1);const {data,error}=await admin.from('store_product_images').insert({product_id:productId,storage_path:path,alt_text:body.alt_text||filename,is_primary:!(existing&&existing.length),sort_order:Number(body.sort_order||0)}).select().single();if(error)throw error;return json({ok:true,image:data})}
  if(action==='set_primary_image'){const productId=clean(body.product_id,80),imageId=clean(body.image_id,80);await admin.from('store_product_images').update({is_primary:false}).eq('product_id',productId);const {error}=await admin.from('store_product_images').update({is_primary:true}).eq('id',imageId);if(error)throw error;return json({ok:true})}
  if(action==='delete_image'){const imageId=clean(body.image_id,80);const {data:im}=await admin.from('store_product_images').select('storage_path').eq('id',imageId).maybeSingle();if(im?.storage_path)await admin.storage.from('product-images').remove([im.storage_path]);const {error}=await admin.from('store_product_images').delete().eq('id',imageId);if(error)throw error;return json({ok:true})}

  if(action==='list_programs'){const {data,error}=await admin.from('am_programs').select('*').order('sort_order').order('name');if(error)throw error;return json({programs:data||[]})}
  if(action==='save_program'){const p=body.program||{};const payload={code:clean(p.code,100),audience_code:clean(p.audience_code||'school',40),name:clean(p.name,200),short_description:p.short_description||null,description:p.description||null,base_price:Number(p.base_price||0),currency:clean(p.currency||'EGP',10),pricing_unit:clean(p.pricing_unit||'per_learner',40),duration_label:p.duration_label||null,delivery_modes:Array.isArray(p.delivery_modes)?p.delivery_modes:['on_site'],is_active:p.is_active!==false,is_featured:!!p.is_featured,sort_order:Number(p.sort_order||999),updated_at:now()};if(!payload.code||!payload.name)return json({error:'CODE_AND_NAME_REQUIRED'},400);const r=p.id?await admin.from('am_programs').update(payload).eq('id',p.id).select().single():await admin.from('am_programs').insert(payload).select().single();if(r.error)throw r.error;return json({ok:true,program:r.data})}
  if(action==='delete_program'){const {error}=await admin.from('am_programs').delete().eq('id',clean(body.id,80));if(error)throw error;return json({ok:true})}
  if(action==='list_addons'){const {data,error}=await admin.from('am_program_addons').select('*').order('sort_order').order('name');if(error)throw error;return json({addons:data||[]})}
  if(action==='save_addon'){const a=body.addon||{};const payload={code:clean(a.code,100),name:clean(a.name,200),description:a.description||null,unit_price:Number(a.unit_price||0),currency:clean(a.currency||'EGP',10),pricing_unit:clean(a.pricing_unit||'per_learner',40),is_active:a.is_active!==false,sort_order:Number(a.sort_order||999),updated_at:now()};if(!payload.code||!payload.name)return json({error:'CODE_AND_NAME_REQUIRED'},400);const r=a.id?await admin.from('am_program_addons').update(payload).eq('id',a.id).select().single():await admin.from('am_program_addons').insert(payload).select().single();if(r.error)throw r.error;return json({ok:true,addon:r.data})}
  if(action==='delete_addon'){const {error}=await admin.from('am_program_addons').delete().eq('id',clean(body.id,80));if(error)throw error;return json({ok:true})}

  if(action==='list_requests'){let q=admin.from('am_requests').select('*,am_institutions(name,institution_type),am_programs(name)').order('created_at',{ascending:false});if(body.status&&body.status!=='all')q=q.eq('status',body.status);const {data,error}=await q.limit(300);if(error)throw error;return json({requests:data||[]})}
  if(action==='get_request'){const id=clean(body.id,80);const [r,it,mt,ev,qt]=await Promise.all([admin.from('am_requests').select('*,am_institutions(*),am_programs(*)').eq('id',id).single(),admin.from('am_request_items').select('*').eq('request_id',id).order('created_at'),admin.from('am_meetings').select('*').eq('request_id',id).order('created_at'),admin.from('am_request_events').select('*').eq('request_id',id).order('created_at',{ascending:false}),admin.from('am_quotations').select('*').eq('request_id',id).order('version_no',{ascending:false})]);if(r.error)throw r.error;return json({request:r.data,items:it.data||[],meetings:mt.data||[],events:ev.data||[],quotations:qt.data||[]})}
  if(action==='update_request_status'){const id=clean(body.id,80),status=clean(body.status,40),allowed=['new','reviewing','contacted','quotation_pending','quotation_sent','approved','execution','completed','rejected','closed','cancelled'];if(!allowed.includes(status))return json({error:'INVALID_STATUS'},400);const {data:old}=await admin.from('am_requests').select('status,email,mobile').eq('id',id).single();const {data,error}=await admin.from('am_requests').update({status,updated_at:now()}).eq('id',id).select().single();if(error)throw error;await admin.from('am_request_events').insert({request_id:id,event_type:'status_changed',from_status:old?.status||null,to_status:status,title:`Status updated to ${status.replaceAll('_',' ')}`,detail:clean(body.detail||'',1000)||null,visibility:'customer',actor_type:'staff',actor_staff_id:staff.user_id});await admin.from('am_customer_notifications').insert({request_id:id,channel:'portal',recipient:old?.email||old?.mobile||null,template_code:'request_status_changed',subject:'Request status updated',payload:{status},status:'sent',sent_at:now()});return json({ok:true,request:data})}

  if(action==='list_quotations'){let q=admin.from('am_quotations').select('*,am_requests(request_number,contact_person,email,mobile,audience_code,status,am_institutions(name))').order('created_at',{ascending:false});if(body.status&&body.status!=='all')q=q.eq('status',body.status);const {data,error}=await q.limit(300);if(error)throw error;return json({quotations:data||[]})}
  if(action==='get_quotation'){const id=clean(body.id,80);const [q,it]=await Promise.all([admin.from('am_quotations').select('*,am_requests(*,am_institutions(*))').eq('id',id).single(),admin.from('am_quotation_items').select('*').eq('quotation_id',id).order('sort_order')]);if(q.error)throw q.error;return json({quotation:q.data,items:it.data||[]})}
  if(action==='create_quotation'){
   const requestId=clean(body.request_id,80);const {data:reqRow,error:reqErr}=await admin.from('am_requests').select('*').eq('id',requestId).single();if(reqErr)throw reqErr;
   const {data:maxRows}=await admin.from('am_quotations').select('version_no').eq('request_id',requestId).order('version_no',{ascending:false}).limit(1);const version=(maxRows?.[0]?.version_no||0)+1;
   const validUntil=body.valid_until||new Date(Date.now()+14*86400000).toISOString().slice(0,10);const qIns=await admin.from('am_quotations').insert({request_id:requestId,version_no:version,status:'draft',currency:reqRow.currency||'EGP',valid_until:validUntil,terms:clean(body.terms||'Subject to availability and written confirmation.',3000),notes:clean(body.notes||'',3000)||null,created_by:staff.user_id}).select().single();if(qIns.error)throw qIns.error;
   let items=Array.isArray(body.items)?body.items:[];if(!items.length){const {data:src}=await admin.from('am_request_items').select('*').eq('request_id',requestId).order('created_at');items=(src||[]).map((x:any)=>({item_type:x.item_type,ref_id:x.ref_id,name:x.name,description:null,quantity:x.quantity,unit_price:x.unit_price,discount_amount:0,config:x.config}))}
   if(items.length){const rows=items.map((x:any,i:number)=>{const qty=Math.max(0,Number(x.quantity||1)),unit=Math.max(0,Number(x.unit_price||0)),disc=Math.max(0,Number(x.discount_amount||0));return {quotation_id:qIns.data.id,item_type:['program','addon','product','service','custom'].includes(x.item_type)?x.item_type:'custom',ref_id:x.ref_id||null,name:clean(x.name||'Item',200),description:clean(x.description||'',1000)||null,quantity:qty,unit_price:unit,discount_amount:disc,amount:Math.max(0,qty*unit-disc),config:x.config||{},sort_order:i}});const ri=await admin.from('am_quotation_items').insert(rows);if(ri.error)throw ri.error}
   await admin.rpc('am_recalculate_quotation',{p_quotation_id:qIns.data.id});await admin.from('am_requests').update({status:'quotation_pending',updated_at:now()}).eq('id',requestId);await admin.from('am_request_events').insert({request_id:requestId,event_type:'quotation_created',from_status:reqRow.status,to_status:'quotation_pending',title:'Quotation is being prepared',detail:`Quotation ${qIns.data.quotation_number} created.`,visibility:'customer',actor_type:'staff',actor_staff_id:staff.user_id});return json({ok:true,quotation:qIns.data})
  }
  if(action==='save_quotation'){
   const id=clean(body.id,80),q=body.quotation||{};const header={discount_amount:Number(q.discount_amount||0),tax_amount:Number(q.tax_amount||0),valid_until:q.valid_until||null,terms:q.terms||null,notes:q.notes||null,updated_at:now()};const uh=await admin.from('am_quotations').update(header).eq('id',id);if(uh.error)throw uh.error;
   if(Array.isArray(body.items)){await admin.from('am_quotation_items').delete().eq('quotation_id',id);const rows=body.items.map((x:any,i:number)=>{const qty=Math.max(0,Number(x.quantity||1)),unit=Math.max(0,Number(x.unit_price||0)),disc=Math.max(0,Number(x.discount_amount||0));return {quotation_id:id,item_type:['program','addon','product','service','custom'].includes(x.item_type)?x.item_type:'custom',ref_id:x.ref_id||null,name:clean(x.name||'Item',200),description:clean(x.description||'',1000)||null,quantity:qty,unit_price:unit,discount_amount:disc,amount:Math.max(0,qty*unit-disc),config:x.config||{},sort_order:i}});if(rows.length){const ri=await admin.from('am_quotation_items').insert(rows);if(ri.error)throw ri.error}}
   await admin.rpc('am_recalculate_quotation',{p_quotation_id:id});const {data:f}=await admin.from('am_quotations').select('*').eq('id',id).single();return json({ok:true,quotation:f})
  }
  if(action==='send_quotation'){
   const id=clean(body.id,80);const {data:q}=await admin.from('am_quotations').select('*,am_requests(id,status,email,mobile)').eq('id',id).single();if(!q)return json({error:'NOT_FOUND'},404);await admin.from('am_quotations').update({status:'sent',sent_at:now(),updated_at:now()}).eq('id',id);await admin.from('am_requests').update({status:'quotation_sent',updated_at:now()}).eq('id',q.request_id);await admin.from('am_request_events').insert({request_id:q.request_id,event_type:'quotation_sent',from_status:q.am_requests?.status||null,to_status:'quotation_sent',title:'Quotation ready',detail:`Quotation ${q.quotation_number} has been issued.`,visibility:'customer',actor_type:'staff',actor_staff_id:staff.user_id});await admin.from('am_customer_notifications').insert([{request_id:q.request_id,quotation_id:id,channel:'portal',recipient:q.am_requests?.email||q.am_requests?.mobile||null,template_code:'quotation_ready',subject:'Your Aviation Matrix quotation is ready',payload:{quotation_number:q.quotation_number},status:'sent',sent_at:now()},{request_id:q.request_id,quotation_id:id,channel:'email',recipient:q.am_requests?.email||null,template_code:'quotation_ready',subject:'Your Aviation Matrix quotation is ready',payload:{quotation_number:q.quotation_number},status:q.am_requests?.email?'pending':'skipped'}]);return json({ok:true})
  }
  if(action==='mark_quotation_accepted'){
   const id=clean(body.id,80);const {data:q}=await admin.from('am_quotations').select('request_id,quotation_number').eq('id',id).single();if(!q)return json({error:'NOT_FOUND'},404);await admin.from('am_quotations').update({status:'accepted',accepted_at:now(),updated_at:now()}).eq('id',id);await admin.from('am_requests').update({status:'approved',updated_at:now()}).eq('id',q.request_id);await admin.from('am_request_events').insert({request_id:q.request_id,event_type:'quotation_accepted',to_status:'approved',title:'Quotation approved',detail:`Quotation ${q.quotation_number} approved.`,visibility:'customer',actor_type:'staff',actor_staff_id:staff.user_id});return json({ok:true})
  }

  if(action==='list_institutions'){const {data,error}=await admin.from('am_institutions').select('*').order('created_at',{ascending:false}).limit(300);if(error)throw error;return json({institutions:data||[]})}
  if(action==='save_institution'){const x=body.institution||{},payload={institution_type:clean(x.institution_type||'school',40),name:clean(x.name,200),contact_person:x.contact_person||null,email:x.email||null,mobile:x.mobile||null,city:x.city||null,country:x.country||'Egypt',notes:x.notes||null,status:x.status||'active',updated_at:now()};if(!payload.name)return json({error:'NAME_REQUIRED'},400);const r=x.id?await admin.from('am_institutions').update(payload).eq('id',x.id).select().single():await admin.from('am_institutions').insert(payload).select().single();if(r.error)throw r.error;return json({ok:true,institution:r.data})}
  if(action==='get_institution_profile'){const id=clean(body.id,80);const [i,r,m]=await Promise.all([admin.from('am_institutions').select('*').eq('id',id).single(),admin.from('am_requests').select('*').eq('institution_id',id).order('created_at',{ascending:false}),admin.from('am_meetings').select('*').eq('institution_id',id).order('created_at',{ascending:false})]);if(i.error)throw i.error;const reqIds=(r.data||[]).map((x:any)=>x.id);let quotes:any[]=[];if(reqIds.length){const q=await admin.from('am_quotations').select('*').in('request_id',reqIds).order('created_at',{ascending:false});quotes=q.data||[]}return json({institution:i.data,requests:r.data||[],meetings:m.data||[],quotations:quotes})}

  if(action==='list_meetings'){const {data,error}=await admin.from('am_meetings').select('*,am_institutions(name,institution_type),am_requests(request_number)').order('scheduled_at',{ascending:true,nullsFirst:false}).limit(300);if(error)throw error;return json({meetings:data||[]})}
  if(action==='update_meeting_status'){const id=clean(body.id,80),status=clean(body.status,40),allowed=['requested','scheduled','completed','cancelled','no_answer'];if(!allowed.includes(status))return json({error:'INVALID_STATUS'},400);const {data,error}=await admin.from('am_meetings').update({status,updated_at:now()}).eq('id',id).select().single();if(error)throw error;return json({ok:true,meeting:data})}

  return json({error:'INVALID_ACTION'},400);
 }catch(e){console.error(e);return json({error:'SERVER_ERROR',detail:String((e as any)?.message||e)},500)}
});