import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
const enc=new TextEncoder(); const clean=(v:any,n=500)=>String(v??'').trim().slice(0,n); const now=()=>new Date().toISOString();
async function sha256Hex(s:string){const h=await crypto.subtle.digest('SHA-256',enc.encode(s));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function band(score:number,bands:any[]){for(const b of bands||[]){const min=Number(b.min??-Infinity),max=Number(b.max??Infinity);if(score>=min&&score<=max)return clean(b.code||b.label,60)}return ''}
function safePayload(v:any){if(v==null||typeof v!=='object')return {};const walk=(x:any,d=0):any=>{if(d>4)return null;if(Array.isArray(x))return x.slice(0,50).map(y=>walk(y,d+1));if(x&&typeof x==='object'){const o:any={};for(const [k,val] of Object.entries(x).slice(0,80))o[clean(k,80)]=walk(val,d+1);return o}if(typeof x==='string')return clean(x,2000);if(typeof x==='number')return Number.isFinite(x)?x:null;if(typeof x==='boolean')return x;return null};const out=walk(v);return new TextEncoder().encode(JSON.stringify(out)).length<=16384?out:{}}
async function rate(admin:any,scope:string,action:string,max:number,windowSeconds:number){const {data,error}=await admin.rpc('am_check_public_api_rate_limit',{p_scope_hash:scope,p_action:action,p_window_seconds:windowSeconds,p_max_requests:max});if(error)throw error;return data}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const len=Number(req.headers.get('content-length')||0);if(len>262144)return json({error:'REQUEST_TOO_LARGE'},413);
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
 try{
  const body=await req.json(); const action=clean(body.action,80); if(!['my_journey','start_stage','submit_stage'].includes(action))return json({error:'INVALID_ACTION'},400); const rt=clean(body.registration_token,200); if(!rt)return json({error:'REGISTRATION_SESSION_REQUIRED'},401);
  const th=await sha256Hex(rt);const rs=await rate(admin,th,'assessment_session',240,900);if(!rs?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rs?.retry_after_seconds||60},429);
  const {data:session}=await admin.from('am_registration_sessions').select('id,application_id,expires_at,revoked_at').eq('token_hash',th).maybeSingle();
  if(!session||session.revoked_at||new Date(session.expires_at).getTime()<=Date.now())return json({error:'REGISTRATION_SESSION_EXPIRED'},401);
  await admin.from('am_registration_sessions').update({last_seen_at:now()}).eq('id',session.id);
  const {data:app,error:ae}=await admin.from('am_registration_applications').select('id,application_number,candidate_id,full_name,lifecycle_status,activated_at').eq('id',session.application_id).single(); if(ae)throw ae;
  if(!app.candidate_id)return json({error:'CANDIDATE_NOT_ACTIVATED',detail:'Complete the Phase 1 activation gates before assessment.'},403);const candidateId=app.candidate_id;

  async function ensureJourney(){let {data:j}=await admin.from('am_candidate_assessment_journeys').select('*').eq('candidate_id',candidateId).maybeSingle();if(!j){const {data:first}=await admin.from('am_assessment_stage_registry').select('code').eq('is_active',true).eq('is_required',true).order('stage_order').limit(1).maybeSingle();const ins=await admin.from('am_candidate_assessment_journeys').insert({candidate_id:candidateId,status:'not_started',current_stage_code:first?.code||null}).select().single();if(ins.error)throw ins.error;j=ins.data}return j}

  if(action==='my_journey'){
    await ensureJourney();await admin.rpc('am_refresh_candidate_assessment_state',{p_candidate_id:candidateId});
    const [{data:j},{data:stages},{data:attempts}]=await Promise.all([admin.from('am_candidate_assessment_journeys').select('*').eq('candidate_id',candidateId).single(),admin.from('am_assessment_stage_registry').select('*').eq('is_active',true).order('stage_order'),admin.from('am_candidate_stage_attempts').select('id,stage_code,attempt_no,status,started_at,completed_at,overall_score,level_code,outcome_code,result_json').eq('candidate_id',candidateId).order('started_at',{ascending:false})]);
    return json({candidate:{candidate_id:candidateId,full_name:app.full_name,application_number:app.application_number},journey:j,stages:stages||[],attempts:attempts||[]});
  }

  if(action==='start_stage'){
    const rr=await rate(admin,th,'assessment_start_stage',30,3600);if(!rr?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rr?.retry_after_seconds||60},429);
    const stageCode=clean(body.stage_code,40).toUpperCase();const journey=await ensureJourney();await admin.rpc('am_refresh_candidate_assessment_state',{p_candidate_id:candidateId});
    const {data:j2}=await admin.from('am_candidate_assessment_journeys').select('*').eq('candidate_id',candidateId).single();if(j2.status==='completed')return json({error:'JOURNEY_ALREADY_COMPLETED'},400);if(j2.current_stage_code!==stageCode)return json({error:'STAGE_NOT_AVAILABLE',detail:`Current stage is ${j2.current_stage_code||'none'}.`},409);
    const {data:stage}=await admin.from('am_assessment_stage_registry').select('*').eq('code',stageCode).eq('is_active',true).single();const {data:v}=await admin.from('am_assessment_stage_versions').select('*').eq('stage_id',stage.id).eq('status','published').order('version_no',{ascending:false}).limit(1).maybeSingle();if(!v)return json({error:'STAGE_NOT_PUBLISHED',detail:'This assessment stage has no published approved version yet.'},409);
    const {data:existing}=await admin.from('am_candidate_stage_attempts').select('*').eq('candidate_id',candidateId).eq('stage_code',stageCode).eq('status','in_progress').order('attempt_no',{ascending:false}).limit(1).maybeSingle();let attempt=existing;
    if(!attempt){const {data:last}=await admin.from('am_candidate_stage_attempts').select('attempt_no').eq('candidate_id',candidateId).eq('stage_code',stageCode).order('attempt_no',{ascending:false}).limit(1);const ai=await admin.from('am_candidate_stage_attempts').insert({journey_id:journey.id,candidate_id:candidateId,stage_code:stageCode,stage_version_id:v.id,attempt_no:Number(last?.[0]?.attempt_no||0)+1,status:'in_progress'}).select().single();if(ai.error)throw ai.error;attempt=ai.data;await admin.from('am_candidate_assessment_journeys').update({status:'in_progress',started_at:journey.started_at||now(),last_activity_at:now(),updated_at:now()}).eq('id',journey.id);await admin.rpc('am_append_candidate_lifetime_event',{p_candidate_id:candidateId,p_event_code:'ASSESSMENT_STAGE_STARTED',p_event_domain:'assessment',p_title:`${stage.name} started`,p_detail:`Attempt ${attempt.attempt_no} started.`,p_payload:{stage_code:stageCode,attempt_no:attempt.attempt_no,stage_version:v.version_label},p_source_system:'assessment-public-api',p_source_table:'am_candidate_stage_attempts',p_source_id:attempt.id,p_recorded_by:null})}
    const {data:items,error:ie}=await admin.from('am_assessment_stage_version_items').select('sequence_no,weight,is_required,question_bank(id,code,prompt,scenario_context,question_type,time_limit_seconds,status,question_options(id,option_code,option_text,sequence_no))').eq('stage_version_id',v.id).order('sequence_no');if(ie)throw ie;
    const questions=(items||[]).filter((x:any)=>['approved','published','active'].includes(x.question_bank?.status)).map((x:any)=>({id:x.question_bank.id,code:x.question_bank.code,prompt:x.question_bank.prompt,scenario_context:x.question_bank.scenario_context,question_type:x.question_bank.question_type,time_limit_seconds:x.question_bank.time_limit_seconds,options:(x.question_bank.question_options||[]).sort((a:any,b:any)=>a.sequence_no-b.sequence_no).map((o:any)=>({id:o.id,code:o.option_code,text:o.option_text}))}));if(!questions.length)return json({error:'NO_APPROVED_QUESTIONS',detail:'The published stage version contains no approved question items.'},409);
    return json({attempt:{id:attempt.id,attempt_no:attempt.attempt_no,stage_code:stageCode,started_at:attempt.started_at},stage:{code:stage.code,name:stage.name,instructions:v.instructions,time_limit_minutes:v.time_limit_minutes},questions});
  }

  if(action==='submit_stage'){
    const rr=await rate(admin,th,'assessment_submit_stage',30,3600);if(!rr?.ok)return json({error:'RATE_LIMITED',retry_after_seconds:rr?.retry_after_seconds||60},429);
    const attemptId=clean(body.attempt_id,80);const answers=Array.isArray(body.answers)?body.answers:[];if(!answers.length||answers.length>250)return json({error:'ANSWERS_REQUIRED'},400);
    const {data:attempt,error:atErr}=await admin.from('am_candidate_stage_attempts').select('*,am_assessment_stage_versions(*),am_assessment_stage_registry!am_candidate_stage_attempts_stage_code_fkey(name,assessment_kind)').eq('id',attemptId).eq('candidate_id',candidateId).single();if(atErr)throw atErr;if(attempt.status!=='in_progress')return json({error:'ATTEMPT_NOT_OPEN'},409);
    const {data:items}=await admin.from('am_assessment_stage_version_items').select('question_id,weight,is_required').eq('stage_version_id',attempt.stage_version_id);const allowed=new Set((items||[]).map((x:any)=>String(x.question_id))),required=new Set((items||[]).filter((x:any)=>x.is_required).map((x:any)=>String(x.question_id)));
    const seen=new Set<string>();for(const a of answers){const q=clean(a?.question_id,80);if(!allowed.has(q))return json({error:'INVALID_QUESTION'},400);if(seen.has(q))return json({error:'DUPLICATE_QUESTION_ANSWER'},400);seen.add(q)}for(const q of required)if(!seen.has(q))return json({error:'INCOMPLETE_ATTEMPT',detail:`Missing required question ${q}.`},400);
    const qids=[...seen];const {data:opts,error:oe}=await admin.from('question_options').select('id,question_id').in('question_id',qids);if(oe)throw oe;const optToQ=new Map<string,string>(),hasOpts=new Set<string>();for(const o of opts||[]){optToQ.set(String(o.id),String(o.question_id));hasOpts.add(String(o.question_id))}
    const rows:any[]=[];for(const a of answers){const q=clean(a.question_id,80),oid=clean(a.option_id,80)||null;if(hasOpts.has(q)){if(!oid||optToQ.get(oid)!==q)return json({error:'INVALID_OPTION_FOR_QUESTION'},400)}else if(oid)return json({error:'INVALID_OPTION_FOR_QUESTION'},400);rows.push({attempt_id:attemptId,question_id:q,option_id:oid,answer_payload:safePayload(a.answer_payload),response_time_seconds:a.response_time_seconds==null?null:Math.max(0,Math.min(86400,Number(a.response_time_seconds)||0))})}
    const del=await admin.from('am_candidate_stage_answers').delete().eq('attempt_id',attemptId);if(del.error)throw del.error;const ins=await admin.from('am_candidate_stage_answers').insert(rows);if(ins.error)throw ins.error;
    const optionIds=rows.map((x:any)=>x.option_id).filter(Boolean);let dims:any[]=[];if(optionIds.length){const {data:scores}=await admin.from('question_dimension_scores').select('score,dimension_id,assessment_dimensions(code,name),option_id').in('option_id',optionIds);const agg:any={};for(const s of scores||[]){const code=s.assessment_dimensions?.code||String(s.dimension_id);if(!agg[code])agg[code]={code,name:s.assessment_dimensions?.name||code,total:0,n:0};agg[code].total+=Number(s.score||0);agg[code].n++}dims=Object.values(agg).map((x:any)=>({...x,raw_score:x.n?x.total/x.n:0,normalized_score:x.n?x.total/x.n:0}))}
    if(dims.length){const di=await admin.from('am_candidate_stage_dimension_results').upsert(dims.map((d:any)=>({attempt_id:attemptId,dimension_code:d.code,dimension_name:d.name,raw_score:d.raw_score,normalized_score:d.normalized_score,evidence_json:{source:'question_dimension_scores'}})),{onConflict:'attempt_id,dimension_code'});if(di.error)throw di.error}
    const overall=dims.length?dims.reduce((s:number,d:any)=>s+Number(d.normalized_score||0),0)/dims.length:null,bands=attempt.am_assessment_stage_versions?.level_bands||[],level=overall==null?'':band(Number(overall),bands),result={dimensions:dims.map((d:any)=>({code:d.code,name:d.name,score:d.normalized_score})),stage_kind:attempt.am_assessment_stage_registry?.assessment_kind||null,scoring_status:dims.length?'scored':'completed_no_scoring_dimensions'};
    const up=await admin.from('am_candidate_stage_attempts').update({status:'completed',submitted_at:now(),completed_at:now(),overall_score:overall,level_code:level||null,outcome_code:level?'level_assigned':'completed',result_json:result,updated_at:now()}).eq('id',attemptId).select().single();if(up.error)throw up.error;
    const ev=await admin.from('am_candidate_evidence').insert({candidate_id:candidateId,evidence_type:'assessment_stage_result',source_system:'assessment-public-api',source_table:'am_candidate_stage_attempts',source_id:attemptId,title:`${attempt.stage_code} assessment result`,summary:level?`Level ${level}`:'Assessment stage completed',status:'verified',issued_at:now(),verified_at:now(),score:overall,metadata:{stage_code:attempt.stage_code,attempt_no:attempt.attempt_no,level_code:level||null,result}}).select().single();if(ev.error)throw ev.error;
    await admin.rpc('am_append_candidate_lifetime_event',{p_candidate_id:candidateId,p_event_code:'ASSESSMENT_STAGE_COMPLETED',p_event_domain:'assessment',p_title:`${attempt.stage_code} assessment completed`,p_detail:level?`Attempt ${attempt.attempt_no} completed at level ${level}.`:`Attempt ${attempt.attempt_no} completed.`,p_payload:{stage_code:attempt.stage_code,attempt_no:attempt.attempt_no,overall_score:overall,level_code:level||null},p_source_system:'assessment-public-api',p_source_table:'am_candidate_stage_attempts',p_source_id:attemptId,p_evidence_id:ev.data.id,p_recorded_by:null});
    if(attempt.stage_code==='TRAITS'){const {data:cs}=await admin.from('am_candidate_current_state').select('state_json').eq('candidate_id',candidateId).maybeSingle();await admin.from('am_candidate_current_state').update({state_json:{...(cs?.state_json||{}),traits_profile:result.dimensions,traits_attempt_id:attemptId},latest_assessment_at:now(),updated_at:now()}).eq('candidate_id',candidateId)}
    await admin.rpc('am_refresh_candidate_assessment_state',{p_candidate_id:candidateId});const {data:j}=await admin.from('am_candidate_assessment_journeys').select('*').eq('candidate_id',candidateId).single();return json({ok:true,result:{overall_score:overall,level_code:level||null,dimensions:result.dimensions},journey:j});
  }
  return json({error:'INVALID_ACTION'},400);
 }catch(e){console.error('assessment-public-api',e);return json({error:'SERVER_ERROR'},500)}
});