ALTER TABLE assessment.accepted_answers ADD CONSTRAINT accepted_answers_pkey PRIMARY KEY (id);
ALTER TABLE assessment.assessment_banks ADD CONSTRAINT assessment_banks_pkey PRIMARY KEY (id);
ALTER TABLE assessment.competencies ADD CONSTRAINT competencies_pkey PRIMARY KEY (id);
ALTER TABLE assessment.deployment_gate_runs ADD CONSTRAINT deployment_gate_runs_pkey PRIMARY KEY (id);
ALTER TABLE assessment.difficulty_distribution_targets ADD CONSTRAINT difficulty_distribution_targets_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_assembly_attempts ADD CONSTRAINT form_assembly_attempts_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_assembly_runs ADD CONSTRAINT form_assembly_runs_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_blueprint_requirements ADD CONSTRAINT form_blueprint_requirements_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_finalization_runs ADD CONSTRAINT form_finalization_runs_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_items ADD CONSTRAINT form_items_pkey PRIMARY KEY (id);
ALTER TABLE assessment.form_versions ADD CONSTRAINT form_versions_pkey PRIMARY KEY (id);
ALTER TABLE assessment.forms ADD CONSTRAINT forms_pkey PRIMARY KEY (id);
ALTER TABLE assessment.item_lo_mappings ADD CONSTRAINT item_lo_mappings_pkey PRIMARY KEY (id);
ALTER TABLE assessment.item_options ADD CONSTRAINT item_options_pkey PRIMARY KEY (id);
ALTER TABLE assessment.item_review_actions ADD CONSTRAINT item_review_actions_pkey PRIMARY KEY (id);
ALTER TABLE assessment.item_scoring_keys ADD CONSTRAINT item_scoring_keys_pkey PRIMARY KEY (id);
ALTER TABLE assessment.item_versions ADD CONSTRAINT item_versions_pkey PRIMARY KEY (id);
ALTER TABLE assessment.items ADD CONSTRAINT items_pkey PRIMARY KEY (id);
ALTER TABLE assessment.learning_outcomes ADD CONSTRAINT learning_outcomes_pkey PRIMARY KEY (id);
ALTER TABLE assessment.listening_stimulus_audio ADD CONSTRAINT listening_stimulus_audio_pkey PRIMARY KEY (stimulus_version_id);
ALTER TABLE assessment.lo_capacity_requirements ADD CONSTRAINT lo_capacity_requirements_pkey PRIMARY KEY (id);
ALTER TABLE assessment.phase06_expected_item_identities ADD CONSTRAINT phase06_expected_item_identities_pkey PRIMARY KEY (id);
ALTER TABLE assessment.phase06_item_import_batches ADD CONSTRAINT phase06_item_import_batches_pkey PRIMARY KEY (id);
ALTER TABLE assessment.phase06_item_import_findings ADD CONSTRAINT phase06_item_import_findings_pkey PRIMARY KEY (id);
ALTER TABLE assessment.phase06_item_source_documents ADD CONSTRAINT phase06_item_source_documents_pkey PRIMARY KEY (id);
ALTER TABLE assessment.phase06_reviewers ADD CONSTRAINT phase06_reviewers_pkey PRIMARY KEY (auth_user_id);
ALTER TABLE assessment.pilot_cohorts ADD CONSTRAINT pilot_cohorts_pkey PRIMARY KEY (id);
ALTER TABLE assessment.psychometric_stats ADD CONSTRAINT psychometric_stats_pkey PRIMARY KEY (id);
ALTER TABLE assessment.qa_defects ADD CONSTRAINT qa_defects_pkey PRIMARY KEY (id);
ALTER TABLE assessment.qa_reviews ADD CONSTRAINT qa_reviews_pkey PRIMARY KEY (id);
ALTER TABLE assessment.ref_balance_pool_gates ADD CONSTRAINT ref_balance_pool_gates_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_constructs ADD CONSTRAINT ref_constructs_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_defect_codes ADD CONSTRAINT ref_defect_codes_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_deployment_gate_checks ADD CONSTRAINT ref_deployment_gate_checks_pkey PRIMARY KEY (check_code);
ALTER TABLE assessment.ref_domains ADD CONSTRAINT ref_domains_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_form_assembly_pool_gates ADD CONSTRAINT ref_form_assembly_pool_gates_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_hydration_tiers ADD CONSTRAINT ref_hydration_tiers_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_item_review_actions ADD CONSTRAINT ref_item_review_actions_pkey PRIMARY KEY (action_code);
ALTER TABLE assessment.ref_item_types ADD CONSTRAINT ref_item_types_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_qa_gates ADD CONSTRAINT ref_qa_gates_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_remediation_actions ADD CONSTRAINT ref_remediation_actions_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_scoring_modes ADD CONSTRAINT ref_scoring_modes_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_source_expectations ADD CONSTRAINT ref_source_expectations_pkey PRIMARY KEY (code);
ALTER TABLE assessment.ref_source_states ADD CONSTRAINT ref_source_states_pkey PRIMARY KEY (code);
ALTER TABLE assessment.registry_source_documents ADD CONSTRAINT registry_source_documents_pkey PRIMARY KEY (id);
ALTER TABLE assessment.releases ADD CONSTRAINT releases_pkey PRIMARY KEY (id);
ALTER TABLE assessment.stimuli ADD CONSTRAINT stimuli_pkey PRIMARY KEY (id);
ALTER TABLE assessment.stimulus_versions ADD CONSTRAINT stimulus_versions_pkey PRIMARY KEY (id);

ALTER TABLE assessment.accepted_answers ADD CONSTRAINT accepted_answers_item_version_id_normalized_value_key UNIQUE (item_version_id, normalized_value);
ALTER TABLE assessment.assessment_banks ADD CONSTRAINT assessment_banks_bank_code_key UNIQUE (bank_code);
ALTER TABLE assessment.competencies ADD CONSTRAINT competencies_competency_code_key UNIQUE (competency_code);
ALTER TABLE assessment.difficulty_distribution_targets ADD CONSTRAINT difficulty_distribution_targe_bank_id_cefr_level_skill_code_key UNIQUE (bank_id, cefr_level, skill_code, difficulty_band);
ALTER TABLE assessment.form_assembly_attempts ADD CONSTRAINT form_assembly_attempts_run_id_attempt_number_key UNIQUE (run_id, attempt_number);
ALTER TABLE assessment.form_assembly_attempts ADD CONSTRAINT form_assembly_attempts_run_id_seed_key UNIQUE (run_id, seed);
ALTER TABLE assessment.form_blueprint_requirements ADD CONSTRAINT form_blueprint_requirements_bank_id_cefr_level_skill_code_key UNIQUE (bank_id, cefr_level, skill_code);
ALTER TABLE assessment.form_items ADD CONSTRAINT form_items_form_version_id_item_version_id_key UNIQUE (form_version_id, item_version_id);
ALTER TABLE assessment.form_items ADD CONSTRAINT form_items_form_version_id_slot_number_key UNIQUE (form_version_id, slot_number);
ALTER TABLE assessment.form_versions ADD CONSTRAINT form_versions_form_id_version_major_version_minor_key UNIQUE (form_id, version_major, version_minor);
ALTER TABLE assessment.forms ADD CONSTRAINT forms_bank_id_cefr_level_form_family_key UNIQUE (bank_id, cefr_level, form_family);
ALTER TABLE assessment.forms ADD CONSTRAINT forms_bank_id_form_code_key UNIQUE (bank_id, form_code);
ALTER TABLE assessment.item_lo_mappings ADD CONSTRAINT item_lo_mappings_item_version_id_lo_id_mapping_role_key UNIQUE (item_version_id, lo_id, mapping_role);
ALTER TABLE assessment.item_options ADD CONSTRAINT item_options_item_version_id_canonical_order_key UNIQUE (item_version_id, canonical_order);
ALTER TABLE assessment.item_options ADD CONSTRAINT item_options_item_version_id_option_code_key UNIQUE (item_version_id, option_code);
ALTER TABLE assessment.item_scoring_keys ADD CONSTRAINT item_scoring_keys_item_version_id_key UNIQUE (item_version_id);
ALTER TABLE assessment.item_versions ADD CONSTRAINT item_versions_item_id_version_major_version_minor_key UNIQUE (item_id, version_major, version_minor);
ALTER TABLE assessment.items ADD CONSTRAINT items_bank_id_item_code_key UNIQUE (bank_id, item_code);
ALTER TABLE assessment.items ADD CONSTRAINT items_bank_id_skill_code_cefr_level_sequence_number_key UNIQUE (bank_id, skill_code, cefr_level, sequence_number);
ALTER TABLE assessment.learning_outcomes ADD CONSTRAINT learning_outcomes_lo_code_key UNIQUE (lo_code);
ALTER TABLE assessment.lo_capacity_requirements ADD CONSTRAINT lo_capacity_requirements_bank_id_lo_id_key UNIQUE (bank_id, lo_id);
ALTER TABLE assessment.phase06_expected_item_identities ADD CONSTRAINT phase06_expected_item_identit_bank_id_skill_code_cefr_level_key UNIQUE (bank_id, skill_code, cefr_level, sequence_number);
ALTER TABLE assessment.phase06_expected_item_identities ADD CONSTRAINT phase06_expected_item_identities_bank_id_item_code_key UNIQUE (bank_id, item_code);
ALTER TABLE assessment.phase06_item_import_batches ADD CONSTRAINT phase06_item_import_batches_batch_code_key UNIQUE (batch_code);
ALTER TABLE assessment.phase06_item_source_documents ADD CONSTRAINT phase06_item_source_documents_source_code_key UNIQUE (source_code);
ALTER TABLE assessment.pilot_cohorts ADD CONSTRAINT pilot_cohorts_bank_id_cohort_code_key UNIQUE (bank_id, cohort_code);
ALTER TABLE assessment.registry_source_documents ADD CONSTRAINT registry_source_documents_source_code_key UNIQUE (source_code);
ALTER TABLE assessment.releases ADD CONSTRAINT releases_bank_id_release_code_key UNIQUE (bank_id, release_code);
ALTER TABLE assessment.releases ADD CONSTRAINT releases_bank_id_release_number_key UNIQUE (bank_id, release_number);
ALTER TABLE assessment.stimuli ADD CONSTRAINT stimuli_bank_id_stimulus_code_key UNIQUE (bank_id, stimulus_code);
ALTER TABLE assessment.stimulus_versions ADD CONSTRAINT stimulus_versions_stimulus_id_version_major_version_minor_key UNIQUE (stimulus_id, version_major, version_minor);

-- Historical migrations 0078 assumes these named constraints already exist.
ALTER TABLE assessment.deployment_gate_runs ADD CONSTRAINT deployment_gate_runs_gate_scope_check CHECK (gate_scope = ANY (ARRAY['FOUNDATION_DEPLOYMENT'::text, 'PHASE06_LAUNCH'::text, 'PHASE11_INTEGRATED'::text]));
ALTER TABLE assessment.ref_deployment_gate_checks ADD CONSTRAINT ref_deployment_gate_checks_gate_scope_check CHECK (gate_scope = ANY (ARRAY['FOUNDATION_DEPLOYMENT'::text, 'PHASE06_LAUNCH'::text, 'PHASE11_INTEGRATED'::text]));
